{
 "title": "OpenTP - Market Data",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Fan Out",
   "type": "graph",
   "description": "Ration of quotes send to quotes received, indication fanout of this component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "quotes_sent/quotes_received" }
   ]
  },
  {
   "title": "Conflation Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "conflator_quotes_received/conflator_quotes_sent"
    }
   ]
  },
  {
   "title": "Outbound Subscriptions",
   "type": "graph",
   "description": "Shows the number of unique subscriptions to quotes made by this component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "outbound_subscriptions" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "The number of active connections to the component",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "active_connections" }
   ]
  }
 ]
}