{
 "title": "OpenTP - Orders",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Orders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "total_orders" }
   ]
  },
  {
   "title": "Filled Orders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "filled_orders" }
   ]
  },
  {
   "title": "Live Orders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "live_orders" }
   ]
  },
  {
   "title": "Cancelled Orders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cancelled_orders" }
   ]
  },
  {
   "title": "Pending Live Orders",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pending_live_orders" }
   ]
  },
  {
   "title": "Pending Cancel Orders",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pending_cancel_orders" }
   ]
  }
 ]
}