FROM golang:1.13
RUN go get -u github.com/go-delve/delve/cmd/dlv
ADD . /app
WORKDIR /app


COPY service_test .


EXPOSE 40000
ENTRYPOINT ["/go/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "./service_test"]
