apiVersion: v1
kind: Service
metadata:
  name: xvwap-order-gateway
  labels:
    app: xvwap-order-gateway
spec:
  ports:
  - port: 50551
    name: api
  clusterIP: None
  selector:
    app: xvwap-order-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: xvwap-order-gateway
  name: xvwap-order-gateway
spec:
  serviceName: "xvwap-order-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: xvwap-order-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: xvwap-order-gateway
        servicetype: execution-venue 
        mic: XVWAP
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ettec/opentp:vwap-strategy-latest
        imagePullPolicy: Always
        name: xvwap-order-gateway
        ports:
        - containerPort: 50551 
          name: api 
