// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

public interface ComplexEventDatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Common.ComplexEventDates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Common.ComplexEventTimes complex_event_times = 1 [(.fix.field_added) = VERSION_FIX_5_0SP1];</code>
   */
  java.util.List<org.fixprotocol.components.ComplexEventTimes> 
      getComplexEventTimesList();
  /**
   * <code>repeated .Common.ComplexEventTimes complex_event_times = 1 [(.fix.field_added) = VERSION_FIX_5_0SP1];</code>
   */
  org.fixprotocol.components.ComplexEventTimes getComplexEventTimes(int index);
  /**
   * <code>repeated .Common.ComplexEventTimes complex_event_times = 1 [(.fix.field_added) = VERSION_FIX_5_0SP1];</code>
   */
  int getComplexEventTimesCount();
  /**
   * <code>repeated .Common.ComplexEventTimes complex_event_times = 1 [(.fix.field_added) = VERSION_FIX_5_0SP1];</code>
   */
  java.util.List<? extends org.fixprotocol.components.ComplexEventTimesOrBuilder> 
      getComplexEventTimesOrBuilderList();
  /**
   * <code>repeated .Common.ComplexEventTimes complex_event_times = 1 [(.fix.field_added) = VERSION_FIX_5_0SP1];</code>
   */
  org.fixprotocol.components.ComplexEventTimesOrBuilder getComplexEventTimesOrBuilder(
      int index);

  /**
   * <code>.fix.Timestamp complex_event_end_date = 2 [(.fix.tag) = 1493, (.fix.type) = DATATYPE_UTC_TIMESTAMP, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return Whether the complexEventEndDate field is set.
   */
  boolean hasComplexEventEndDate();
  /**
   * <code>.fix.Timestamp complex_event_end_date = 2 [(.fix.tag) = 1493, (.fix.type) = DATATYPE_UTC_TIMESTAMP, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return The complexEventEndDate.
   */
  org.fixprotocol.components.Fix.Timestamp getComplexEventEndDate();
  /**
   * <code>.fix.Timestamp complex_event_end_date = 2 [(.fix.tag) = 1493, (.fix.type) = DATATYPE_UTC_TIMESTAMP, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   */
  org.fixprotocol.components.Fix.TimestampOrBuilder getComplexEventEndDateOrBuilder();

  /**
   * <code>.fix.Timestamp complex_event_start_date = 3 [(.fix.tag) = 1492, (.fix.type) = DATATYPE_UTC_TIMESTAMP, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return Whether the complexEventStartDate field is set.
   */
  boolean hasComplexEventStartDate();
  /**
   * <code>.fix.Timestamp complex_event_start_date = 3 [(.fix.tag) = 1492, (.fix.type) = DATATYPE_UTC_TIMESTAMP, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return The complexEventStartDate.
   */
  org.fixprotocol.components.Fix.Timestamp getComplexEventStartDate();
  /**
   * <code>.fix.Timestamp complex_event_start_date = 3 [(.fix.tag) = 1492, (.fix.type) = DATATYPE_UTC_TIMESTAMP, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   */
  org.fixprotocol.components.Fix.TimestampOrBuilder getComplexEventStartDateOrBuilder();
}
