// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf enum {@code Common.ComplexEventPriceTimeTypeEnum}
 */
public enum ComplexEventPriceTimeTypeEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_UNSPECIFIED = 0;</code>
   */
  COMPLEX_EVENT_PRICE_TIME_TYPE_UNSPECIFIED(0),
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_EXPIRATION = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 92];</code>
   */
  COMPLEX_EVENT_PRICE_TIME_TYPE_EXPIRATION(1),
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_IMMEDIATE = 2 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 92];</code>
   */
  COMPLEX_EVENT_PRICE_TIME_TYPE_IMMEDIATE(2),
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_SPECIFIED_DATE = 3 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 92];</code>
   */
  COMPLEX_EVENT_PRICE_TIME_TYPE_SPECIFIED_DATE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int COMPLEX_EVENT_PRICE_TIME_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_EXPIRATION = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 92];</code>
   */
  public static final int COMPLEX_EVENT_PRICE_TIME_TYPE_EXPIRATION_VALUE = 1;
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_IMMEDIATE = 2 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 92];</code>
   */
  public static final int COMPLEX_EVENT_PRICE_TIME_TYPE_IMMEDIATE_VALUE = 2;
  /**
   * <code>COMPLEX_EVENT_PRICE_TIME_TYPE_SPECIFIED_DATE = 3 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 92];</code>
   */
  public static final int COMPLEX_EVENT_PRICE_TIME_TYPE_SPECIFIED_DATE_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ComplexEventPriceTimeTypeEnum valueOf(int value) {
    return forNumber(value);
  }

  public static ComplexEventPriceTimeTypeEnum forNumber(int value) {
    switch (value) {
      case 0: return COMPLEX_EVENT_PRICE_TIME_TYPE_UNSPECIFIED;
      case 1: return COMPLEX_EVENT_PRICE_TIME_TYPE_EXPIRATION;
      case 2: return COMPLEX_EVENT_PRICE_TIME_TYPE_IMMEDIATE;
      case 3: return COMPLEX_EVENT_PRICE_TIME_TYPE_SPECIFIED_DATE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ComplexEventPriceTimeTypeEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ComplexEventPriceTimeTypeEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ComplexEventPriceTimeTypeEnum>() {
          public ComplexEventPriceTimeTypeEnum findValueByNumber(int number) {
            return ComplexEventPriceTimeTypeEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.getDescriptor().getEnumTypes().get(205);
  }

  private static final ComplexEventPriceTimeTypeEnum[] VALUES = values();

  public static ComplexEventPriceTimeTypeEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ComplexEventPriceTimeTypeEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Common.ComplexEventPriceTimeTypeEnum)
}

