// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf enum {@code Common.ContAmtTypeEnum}
 */
public enum ContAmtTypeEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CONT_AMT_TYPE_UNSPECIFIED = 0;</code>
   */
  CONT_AMT_TYPE_UNSPECIFIED(0),
  /**
   * <code>CONT_AMT_TYPE_COMMISSION_AMOUNT = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_COMMISSION_AMOUNT(1),
  /**
   * <code>CONT_AMT_TYPE_COMMISSION_PERCENT = 2 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_COMMISSION_PERCENT(2),
  /**
   * <code>CONT_AMT_TYPE_DILUTION_LEVY_AMOUNT = 3 [(.fix.enum_value) = "7", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_DILUTION_LEVY_AMOUNT(3),
  /**
   * <code>CONT_AMT_TYPE_DILUTION_LEVY_PERCENT = 4 [(.fix.enum_value) = "8", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_DILUTION_LEVY_PERCENT(4),
  /**
   * <code>CONT_AMT_TYPE_DISCOUNT_AMOUNT = 5 [(.fix.enum_value) = "5", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_DISCOUNT_AMOUNT(5),
  /**
   * <code>CONT_AMT_TYPE_DISCOUNT_PERCENT = 6 [(.fix.enum_value) = "6", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_DISCOUNT_PERCENT(6),
  /**
   * <code>CONT_AMT_TYPE_EXIT_CHARGE_AMOUNT = 7 [(.fix.enum_value) = "9", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_EXIT_CHARGE_AMOUNT(7),
  /**
   * <code>CONT_AMT_TYPE_EXIT_CHARGE_PERCENT = 8 [(.fix.enum_value) = "10", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_EXIT_CHARGE_PERCENT(8),
  /**
   * <code>CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_FUND = 9 [(.fix.enum_value) = "14", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_FUND(9),
  /**
   * <code>CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_ORDER = 10 [(.fix.enum_value) = "13", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_ORDER(10),
  /**
   * <code>CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_PERCENT = 11 [(.fix.enum_value) = "11", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_PERCENT(11),
  /**
   * <code>CONT_AMT_TYPE_INITIAL_CHARGE_AMOUNT = 12 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_INITIAL_CHARGE_AMOUNT(12),
  /**
   * <code>CONT_AMT_TYPE_INITIAL_CHARGE_PERCENT = 13 [(.fix.enum_value) = "4", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_INITIAL_CHARGE_PERCENT(13),
  /**
   * <code>CONT_AMT_TYPE_NET_SETTLEMENT_AMOUNT = 14 [(.fix.enum_value) = "15", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_NET_SETTLEMENT_AMOUNT(14),
  /**
   * <code>CONT_AMT_TYPE_PROJECTED_FUND_VALUE = 15 [(.fix.enum_value) = "12", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  CONT_AMT_TYPE_PROJECTED_FUND_VALUE(15),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CONT_AMT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int CONT_AMT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CONT_AMT_TYPE_COMMISSION_AMOUNT = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_COMMISSION_AMOUNT_VALUE = 1;
  /**
   * <code>CONT_AMT_TYPE_COMMISSION_PERCENT = 2 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_COMMISSION_PERCENT_VALUE = 2;
  /**
   * <code>CONT_AMT_TYPE_DILUTION_LEVY_AMOUNT = 3 [(.fix.enum_value) = "7", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_DILUTION_LEVY_AMOUNT_VALUE = 3;
  /**
   * <code>CONT_AMT_TYPE_DILUTION_LEVY_PERCENT = 4 [(.fix.enum_value) = "8", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_DILUTION_LEVY_PERCENT_VALUE = 4;
  /**
   * <code>CONT_AMT_TYPE_DISCOUNT_AMOUNT = 5 [(.fix.enum_value) = "5", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_DISCOUNT_AMOUNT_VALUE = 5;
  /**
   * <code>CONT_AMT_TYPE_DISCOUNT_PERCENT = 6 [(.fix.enum_value) = "6", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_DISCOUNT_PERCENT_VALUE = 6;
  /**
   * <code>CONT_AMT_TYPE_EXIT_CHARGE_AMOUNT = 7 [(.fix.enum_value) = "9", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_EXIT_CHARGE_AMOUNT_VALUE = 7;
  /**
   * <code>CONT_AMT_TYPE_EXIT_CHARGE_PERCENT = 8 [(.fix.enum_value) = "10", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_EXIT_CHARGE_PERCENT_VALUE = 8;
  /**
   * <code>CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_FUND = 9 [(.fix.enum_value) = "14", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_FUND_VALUE = 9;
  /**
   * <code>CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_ORDER = 10 [(.fix.enum_value) = "13", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_ORDER_VALUE = 10;
  /**
   * <code>CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_PERCENT = 11 [(.fix.enum_value) = "11", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_PERCENT_VALUE = 11;
  /**
   * <code>CONT_AMT_TYPE_INITIAL_CHARGE_AMOUNT = 12 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_INITIAL_CHARGE_AMOUNT_VALUE = 12;
  /**
   * <code>CONT_AMT_TYPE_INITIAL_CHARGE_PERCENT = 13 [(.fix.enum_value) = "4", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_INITIAL_CHARGE_PERCENT_VALUE = 13;
  /**
   * <code>CONT_AMT_TYPE_NET_SETTLEMENT_AMOUNT = 14 [(.fix.enum_value) = "15", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_NET_SETTLEMENT_AMOUNT_VALUE = 14;
  /**
   * <code>CONT_AMT_TYPE_PROJECTED_FUND_VALUE = 15 [(.fix.enum_value) = "12", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int CONT_AMT_TYPE_PROJECTED_FUND_VALUE_VALUE = 15;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ContAmtTypeEnum valueOf(int value) {
    return forNumber(value);
  }

  public static ContAmtTypeEnum forNumber(int value) {
    switch (value) {
      case 0: return CONT_AMT_TYPE_UNSPECIFIED;
      case 1: return CONT_AMT_TYPE_COMMISSION_AMOUNT;
      case 2: return CONT_AMT_TYPE_COMMISSION_PERCENT;
      case 3: return CONT_AMT_TYPE_DILUTION_LEVY_AMOUNT;
      case 4: return CONT_AMT_TYPE_DILUTION_LEVY_PERCENT;
      case 5: return CONT_AMT_TYPE_DISCOUNT_AMOUNT;
      case 6: return CONT_AMT_TYPE_DISCOUNT_PERCENT;
      case 7: return CONT_AMT_TYPE_EXIT_CHARGE_AMOUNT;
      case 8: return CONT_AMT_TYPE_EXIT_CHARGE_PERCENT;
      case 9: return CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_FUND;
      case 10: return CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_ON_ORDER;
      case 11: return CONT_AMT_TYPE_FUND_BASED_RENEWAL_COMMISSION_PERCENT;
      case 12: return CONT_AMT_TYPE_INITIAL_CHARGE_AMOUNT;
      case 13: return CONT_AMT_TYPE_INITIAL_CHARGE_PERCENT;
      case 14: return CONT_AMT_TYPE_NET_SETTLEMENT_AMOUNT;
      case 15: return CONT_AMT_TYPE_PROJECTED_FUND_VALUE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ContAmtTypeEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ContAmtTypeEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ContAmtTypeEnum>() {
          public ContAmtTypeEnum findValueByNumber(int number) {
            return ContAmtTypeEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.getDescriptor().getEnumTypes().get(98);
  }

  private static final ContAmtTypeEnum[] VALUES = values();

  public static ContAmtTypeEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ContAmtTypeEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Common.ContAmtTypeEnum)
}

