// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

public interface FinancingDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Common.FinancingDetails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string agreement_currency = 1 [(.fix.tag) = 918, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getAgreementCurrency();
  /**
   * <code>string agreement_currency = 1 [(.fix.tag) = 918, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getAgreementCurrencyBytes();

  /**
   * <code>sfixed32 agreement_date = 2 [(.fix.tag) = 915, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getAgreementDate();

  /**
   * <code>string agreement_desc = 3 [(.fix.tag) = 913, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getAgreementDesc();
  /**
   * <code>string agreement_desc = 3 [(.fix.tag) = 913, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getAgreementDescBytes();

  /**
   * <code>string agreement_id = 4 [(.fix.tag) = 914, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getAgreementId();
  /**
   * <code>string agreement_id = 4 [(.fix.tag) = 914, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getAgreementIdBytes();

  /**
   * <code>.Common.DeliveryTypeEnum delivery_type = 5 [(.fix.tag) = 919, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getDeliveryTypeValue();
  /**
   * <code>.Common.DeliveryTypeEnum delivery_type = 5 [(.fix.tag) = 919, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.DeliveryTypeEnum getDeliveryType();

  /**
   * <code>sfixed32 end_date = 6 [(.fix.tag) = 917, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getEndDate();

  /**
   * <code>.fix.Decimal64 margin_ratio = 7 [(.fix.tag) = 898, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasMarginRatio();
  /**
   * <code>.fix.Decimal64 margin_ratio = 7 [(.fix.tag) = 898, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getMarginRatio();
  /**
   * <code>.fix.Decimal64 margin_ratio = 7 [(.fix.tag) = 898, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getMarginRatioOrBuilder();

  /**
   * <code>sfixed32 start_date = 8 [(.fix.tag) = 916, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getStartDate();

  /**
   * <code>.Common.TerminationTypeEnum termination_type = 9 [(.fix.tag) = 788, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getTerminationTypeValue();
  /**
   * <code>.Common.TerminationTypeEnum termination_type = 9 [(.fix.tag) = 788, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.TerminationTypeEnum getTerminationType();
}
