// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf type {@code Common.InstrumentPtysSubGrp}
 */
public  final class InstrumentPtysSubGrp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Common.InstrumentPtysSubGrp)
    InstrumentPtysSubGrpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InstrumentPtysSubGrp.newBuilder() to construct.
  private InstrumentPtysSubGrp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InstrumentPtysSubGrp() {
    instrumentPartySubId_ = "";
    instrumentPartySubIdType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InstrumentPtysSubGrp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InstrumentPtysSubGrp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            instrumentPartySubId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            instrumentPartySubIdType_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.internal_static_Common_InstrumentPtysSubGrp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.fixprotocol.components.Common.internal_static_Common_InstrumentPtysSubGrp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.fixprotocol.components.InstrumentPtysSubGrp.class, org.fixprotocol.components.InstrumentPtysSubGrp.Builder.class);
  }

  public static final int INSTRUMENT_PARTY_SUB_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object instrumentPartySubId_;
  /**
   * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.lang.String getInstrumentPartySubId() {
    java.lang.Object ref = instrumentPartySubId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrumentPartySubId_ = s;
      return s;
    }
  }
  /**
   * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public com.google.protobuf.ByteString
      getInstrumentPartySubIdBytes() {
    java.lang.Object ref = instrumentPartySubId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrumentPartySubId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUMENT_PARTY_SUB_ID_TYPE_FIELD_NUMBER = 2;
  private int instrumentPartySubIdType_;
  /**
   * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public int getInstrumentPartySubIdTypeValue() {
    return instrumentPartySubIdType_;
  }
  /**
   * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.InstrumentPartySubIDTypeEnum getInstrumentPartySubIdType() {
    @SuppressWarnings("deprecation")
    org.fixprotocol.components.InstrumentPartySubIDTypeEnum result = org.fixprotocol.components.InstrumentPartySubIDTypeEnum.valueOf(instrumentPartySubIdType_);
    return result == null ? org.fixprotocol.components.InstrumentPartySubIDTypeEnum.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getInstrumentPartySubIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, instrumentPartySubId_);
    }
    if (instrumentPartySubIdType_ != org.fixprotocol.components.InstrumentPartySubIDTypeEnum.INSTRUMENT_PARTY_SUB_ID_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, instrumentPartySubIdType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getInstrumentPartySubIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, instrumentPartySubId_);
    }
    if (instrumentPartySubIdType_ != org.fixprotocol.components.InstrumentPartySubIDTypeEnum.INSTRUMENT_PARTY_SUB_ID_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, instrumentPartySubIdType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.fixprotocol.components.InstrumentPtysSubGrp)) {
      return super.equals(obj);
    }
    org.fixprotocol.components.InstrumentPtysSubGrp other = (org.fixprotocol.components.InstrumentPtysSubGrp) obj;

    if (!getInstrumentPartySubId()
        .equals(other.getInstrumentPartySubId())) return false;
    if (instrumentPartySubIdType_ != other.instrumentPartySubIdType_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INSTRUMENT_PARTY_SUB_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInstrumentPartySubId().hashCode();
    hash = (37 * hash) + INSTRUMENT_PARTY_SUB_ID_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + instrumentPartySubIdType_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.InstrumentPtysSubGrp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.fixprotocol.components.InstrumentPtysSubGrp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Common.InstrumentPtysSubGrp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Common.InstrumentPtysSubGrp)
      org.fixprotocol.components.InstrumentPtysSubGrpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fixprotocol.components.Common.internal_static_Common_InstrumentPtysSubGrp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fixprotocol.components.Common.internal_static_Common_InstrumentPtysSubGrp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fixprotocol.components.InstrumentPtysSubGrp.class, org.fixprotocol.components.InstrumentPtysSubGrp.Builder.class);
    }

    // Construct using org.fixprotocol.components.InstrumentPtysSubGrp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      instrumentPartySubId_ = "";

      instrumentPartySubIdType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.fixprotocol.components.Common.internal_static_Common_InstrumentPtysSubGrp_descriptor;
    }

    @java.lang.Override
    public org.fixprotocol.components.InstrumentPtysSubGrp getDefaultInstanceForType() {
      return org.fixprotocol.components.InstrumentPtysSubGrp.getDefaultInstance();
    }

    @java.lang.Override
    public org.fixprotocol.components.InstrumentPtysSubGrp build() {
      org.fixprotocol.components.InstrumentPtysSubGrp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.fixprotocol.components.InstrumentPtysSubGrp buildPartial() {
      org.fixprotocol.components.InstrumentPtysSubGrp result = new org.fixprotocol.components.InstrumentPtysSubGrp(this);
      result.instrumentPartySubId_ = instrumentPartySubId_;
      result.instrumentPartySubIdType_ = instrumentPartySubIdType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.fixprotocol.components.InstrumentPtysSubGrp) {
        return mergeFrom((org.fixprotocol.components.InstrumentPtysSubGrp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.fixprotocol.components.InstrumentPtysSubGrp other) {
      if (other == org.fixprotocol.components.InstrumentPtysSubGrp.getDefaultInstance()) return this;
      if (!other.getInstrumentPartySubId().isEmpty()) {
        instrumentPartySubId_ = other.instrumentPartySubId_;
        onChanged();
      }
      if (other.instrumentPartySubIdType_ != 0) {
        setInstrumentPartySubIdTypeValue(other.getInstrumentPartySubIdTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.fixprotocol.components.InstrumentPtysSubGrp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.fixprotocol.components.InstrumentPtysSubGrp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object instrumentPartySubId_ = "";
    /**
     * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.lang.String getInstrumentPartySubId() {
      java.lang.Object ref = instrumentPartySubId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrumentPartySubId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentPartySubIdBytes() {
      java.lang.Object ref = instrumentPartySubId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumentPartySubId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setInstrumentPartySubId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      instrumentPartySubId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearInstrumentPartySubId() {
      
      instrumentPartySubId_ = getDefaultInstance().getInstrumentPartySubId();
      onChanged();
      return this;
    }
    /**
     * <code>string instrument_party_sub_id = 1 [(.fix.tag) = 1053, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setInstrumentPartySubIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      instrumentPartySubId_ = value;
      onChanged();
      return this;
    }

    private int instrumentPartySubIdType_ = 0;
    /**
     * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public int getInstrumentPartySubIdTypeValue() {
      return instrumentPartySubIdType_;
    }
    /**
     * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setInstrumentPartySubIdTypeValue(int value) {
      instrumentPartySubIdType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.InstrumentPartySubIDTypeEnum getInstrumentPartySubIdType() {
      @SuppressWarnings("deprecation")
      org.fixprotocol.components.InstrumentPartySubIDTypeEnum result = org.fixprotocol.components.InstrumentPartySubIDTypeEnum.valueOf(instrumentPartySubIdType_);
      return result == null ? org.fixprotocol.components.InstrumentPartySubIDTypeEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setInstrumentPartySubIdType(org.fixprotocol.components.InstrumentPartySubIDTypeEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      instrumentPartySubIdType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Common.InstrumentPartySubIDTypeEnum instrument_party_sub_id_type = 2 [(.fix.tag) = 1054, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearInstrumentPartySubIdType() {
      
      instrumentPartySubIdType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Common.InstrumentPtysSubGrp)
  }

  // @@protoc_insertion_point(class_scope:Common.InstrumentPtysSubGrp)
  private static final org.fixprotocol.components.InstrumentPtysSubGrp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.fixprotocol.components.InstrumentPtysSubGrp();
  }

  public static org.fixprotocol.components.InstrumentPtysSubGrp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstrumentPtysSubGrp>
      PARSER = new com.google.protobuf.AbstractParser<InstrumentPtysSubGrp>() {
    @java.lang.Override
    public InstrumentPtysSubGrp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InstrumentPtysSubGrp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InstrumentPtysSubGrp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InstrumentPtysSubGrp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.fixprotocol.components.InstrumentPtysSubGrp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

