// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf enum {@code Common.MultilegModelEnum}
 */
public enum MultilegModelEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MULTILEG_MODEL_UNSPECIFIED = 0;</code>
   */
  MULTILEG_MODEL_UNSPECIFIED(0),
  /**
   * <code>MULTILEG_MODEL_PREDEFINED_MULTILEG_SECURITY = 1 [(.fix.enum_value) = "0", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 59];</code>
   */
  MULTILEG_MODEL_PREDEFINED_MULTILEG_SECURITY(1),
  /**
   * <code>MULTILEG_MODEL_USER_DEFINED = 2 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 59];</code>
   */
  MULTILEG_MODEL_USER_DEFINED(2),
  /**
   * <code>MULTILEG_MODEL_USER_DEFINED_MULTILEG_SECURITY = 3 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 59];</code>
   */
  MULTILEG_MODEL_USER_DEFINED_MULTILEG_SECURITY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MULTILEG_MODEL_UNSPECIFIED = 0;</code>
   */
  public static final int MULTILEG_MODEL_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MULTILEG_MODEL_PREDEFINED_MULTILEG_SECURITY = 1 [(.fix.enum_value) = "0", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 59];</code>
   */
  public static final int MULTILEG_MODEL_PREDEFINED_MULTILEG_SECURITY_VALUE = 1;
  /**
   * <code>MULTILEG_MODEL_USER_DEFINED = 2 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 59];</code>
   */
  public static final int MULTILEG_MODEL_USER_DEFINED_VALUE = 2;
  /**
   * <code>MULTILEG_MODEL_USER_DEFINED_MULTILEG_SECURITY = 3 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 59];</code>
   */
  public static final int MULTILEG_MODEL_USER_DEFINED_MULTILEG_SECURITY_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MultilegModelEnum valueOf(int value) {
    return forNumber(value);
  }

  public static MultilegModelEnum forNumber(int value) {
    switch (value) {
      case 0: return MULTILEG_MODEL_UNSPECIFIED;
      case 1: return MULTILEG_MODEL_PREDEFINED_MULTILEG_SECURITY;
      case 2: return MULTILEG_MODEL_USER_DEFINED;
      case 3: return MULTILEG_MODEL_USER_DEFINED_MULTILEG_SECURITY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MultilegModelEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MultilegModelEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MultilegModelEnum>() {
          public MultilegModelEnum findValueByNumber(int number) {
            return MultilegModelEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.getDescriptor().getEnumTypes().get(167);
  }

  private static final MultilegModelEnum[] VALUES = values();

  public static MultilegModelEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MultilegModelEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Common.MultilegModelEnum)
}

