// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf enum {@code Common.PegOffsetTypeEnum}
 */
public enum PegOffsetTypeEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PEG_OFFSET_TYPE_UNSPECIFIED = 0;</code>
   */
  PEG_OFFSET_TYPE_UNSPECIFIED(0),
  /**
   * <code>PEG_OFFSET_TYPE_BASIS_POINTS = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  PEG_OFFSET_TYPE_BASIS_POINTS(1),
  /**
   * <code>PEG_OFFSET_TYPE_PRICE = 2 [(.fix.enum_value) = "0", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  PEG_OFFSET_TYPE_PRICE(2),
  /**
   * <code>PEG_OFFSET_TYPE_PRICE_TIER = 3 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  PEG_OFFSET_TYPE_PRICE_TIER(3),
  /**
   * <code>PEG_OFFSET_TYPE_TICKS = 4 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  PEG_OFFSET_TYPE_TICKS(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PEG_OFFSET_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int PEG_OFFSET_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PEG_OFFSET_TYPE_BASIS_POINTS = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int PEG_OFFSET_TYPE_BASIS_POINTS_VALUE = 1;
  /**
   * <code>PEG_OFFSET_TYPE_PRICE = 2 [(.fix.enum_value) = "0", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int PEG_OFFSET_TYPE_PRICE_VALUE = 2;
  /**
   * <code>PEG_OFFSET_TYPE_PRICE_TIER = 3 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int PEG_OFFSET_TYPE_PRICE_TIER_VALUE = 3;
  /**
   * <code>PEG_OFFSET_TYPE_TICKS = 4 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int PEG_OFFSET_TYPE_TICKS_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PegOffsetTypeEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PegOffsetTypeEnum forNumber(int value) {
    switch (value) {
      case 0: return PEG_OFFSET_TYPE_UNSPECIFIED;
      case 1: return PEG_OFFSET_TYPE_BASIS_POINTS;
      case 2: return PEG_OFFSET_TYPE_PRICE;
      case 3: return PEG_OFFSET_TYPE_PRICE_TIER;
      case 4: return PEG_OFFSET_TYPE_TICKS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PegOffsetTypeEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PegOffsetTypeEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PegOffsetTypeEnum>() {
          public PegOffsetTypeEnum findValueByNumber(int number) {
            return PegOffsetTypeEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.getDescriptor().getEnumTypes().get(54);
  }

  private static final PegOffsetTypeEnum[] VALUES = values();

  public static PegOffsetTypeEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PegOffsetTypeEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Common.PegOffsetTypeEnum)
}

