// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf type {@code Common.PreAllocMlegGrp}
 */
public  final class PreAllocMlegGrp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Common.PreAllocMlegGrp)
    PreAllocMlegGrpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PreAllocMlegGrp.newBuilder() to construct.
  private PreAllocMlegGrp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PreAllocMlegGrp() {
    allocAccount_ = "";
    allocAcctIdSource_ = 0;
    allocSettlCurrency_ = "";
    individualAllocId_ = "";
    nestedParties3_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PreAllocMlegGrp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PreAllocMlegGrp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            allocAccount_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            allocAcctIdSource_ = rawValue;
            break;
          }
          case 26: {
            org.fixprotocol.components.Fix.Decimal64.Builder subBuilder = null;
            if (allocQty_ != null) {
              subBuilder = allocQty_.toBuilder();
            }
            allocQty_ = input.readMessage(org.fixprotocol.components.Fix.Decimal64.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(allocQty_);
              allocQty_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            allocSettlCurrency_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            individualAllocId_ = s;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              nestedParties3_ = new java.util.ArrayList<org.fixprotocol.components.NestedParties3>();
              mutable_bitField0_ |= 0x00000001;
            }
            nestedParties3_.add(
                input.readMessage(org.fixprotocol.components.NestedParties3.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        nestedParties3_ = java.util.Collections.unmodifiableList(nestedParties3_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.internal_static_Common_PreAllocMlegGrp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.fixprotocol.components.Common.internal_static_Common_PreAllocMlegGrp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.fixprotocol.components.PreAllocMlegGrp.class, org.fixprotocol.components.PreAllocMlegGrp.Builder.class);
  }

  public static final int ALLOC_ACCOUNT_FIELD_NUMBER = 1;
  private volatile java.lang.Object allocAccount_;
  /**
   * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.lang.String getAllocAccount() {
    java.lang.Object ref = allocAccount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      allocAccount_ = s;
      return s;
    }
  }
  /**
   * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public com.google.protobuf.ByteString
      getAllocAccountBytes() {
    java.lang.Object ref = allocAccount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      allocAccount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALLOC_ACCT_ID_SOURCE_FIELD_NUMBER = 2;
  private int allocAcctIdSource_;
  /**
   * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public int getAllocAcctIdSourceValue() {
    return allocAcctIdSource_;
  }
  /**
   * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.AllocAcctIDSourceEnum getAllocAcctIdSource() {
    @SuppressWarnings("deprecation")
    org.fixprotocol.components.AllocAcctIDSourceEnum result = org.fixprotocol.components.AllocAcctIDSourceEnum.valueOf(allocAcctIdSource_);
    return result == null ? org.fixprotocol.components.AllocAcctIDSourceEnum.UNRECOGNIZED : result;
  }

  public static final int ALLOC_QTY_FIELD_NUMBER = 3;
  private org.fixprotocol.components.Fix.Decimal64 allocQty_;
  /**
   * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public boolean hasAllocQty() {
    return allocQty_ != null;
  }
  /**
   * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.Fix.Decimal64 getAllocQty() {
    return allocQty_ == null ? org.fixprotocol.components.Fix.Decimal64.getDefaultInstance() : allocQty_;
  }
  /**
   * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.Fix.Decimal64OrBuilder getAllocQtyOrBuilder() {
    return getAllocQty();
  }

  public static final int ALLOC_SETTL_CURRENCY_FIELD_NUMBER = 4;
  private volatile java.lang.Object allocSettlCurrency_;
  /**
   * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.lang.String getAllocSettlCurrency() {
    java.lang.Object ref = allocSettlCurrency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      allocSettlCurrency_ = s;
      return s;
    }
  }
  /**
   * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public com.google.protobuf.ByteString
      getAllocSettlCurrencyBytes() {
    java.lang.Object ref = allocSettlCurrency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      allocSettlCurrency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INDIVIDUAL_ALLOC_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object individualAllocId_;
  /**
   * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.lang.String getIndividualAllocId() {
    java.lang.Object ref = individualAllocId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      individualAllocId_ = s;
      return s;
    }
  }
  /**
   * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public com.google.protobuf.ByteString
      getIndividualAllocIdBytes() {
    java.lang.Object ref = individualAllocId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      individualAllocId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NESTED_PARTIES3_FIELD_NUMBER = 6;
  private java.util.List<org.fixprotocol.components.NestedParties3> nestedParties3_;
  /**
   * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.util.List<org.fixprotocol.components.NestedParties3> getNestedParties3List() {
    return nestedParties3_;
  }
  /**
   * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.util.List<? extends org.fixprotocol.components.NestedParties3OrBuilder> 
      getNestedParties3OrBuilderList() {
    return nestedParties3_;
  }
  /**
   * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public int getNestedParties3Count() {
    return nestedParties3_.size();
  }
  /**
   * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.NestedParties3 getNestedParties3(int index) {
    return nestedParties3_.get(index);
  }
  /**
   * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.NestedParties3OrBuilder getNestedParties3OrBuilder(
      int index) {
    return nestedParties3_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAllocAccountBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, allocAccount_);
    }
    if (allocAcctIdSource_ != org.fixprotocol.components.AllocAcctIDSourceEnum.ALLOC_ACCT_ID_SOURCE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, allocAcctIdSource_);
    }
    if (allocQty_ != null) {
      output.writeMessage(3, getAllocQty());
    }
    if (!getAllocSettlCurrencyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, allocSettlCurrency_);
    }
    if (!getIndividualAllocIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, individualAllocId_);
    }
    for (int i = 0; i < nestedParties3_.size(); i++) {
      output.writeMessage(6, nestedParties3_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAllocAccountBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, allocAccount_);
    }
    if (allocAcctIdSource_ != org.fixprotocol.components.AllocAcctIDSourceEnum.ALLOC_ACCT_ID_SOURCE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, allocAcctIdSource_);
    }
    if (allocQty_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAllocQty());
    }
    if (!getAllocSettlCurrencyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, allocSettlCurrency_);
    }
    if (!getIndividualAllocIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, individualAllocId_);
    }
    for (int i = 0; i < nestedParties3_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, nestedParties3_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.fixprotocol.components.PreAllocMlegGrp)) {
      return super.equals(obj);
    }
    org.fixprotocol.components.PreAllocMlegGrp other = (org.fixprotocol.components.PreAllocMlegGrp) obj;

    if (!getAllocAccount()
        .equals(other.getAllocAccount())) return false;
    if (allocAcctIdSource_ != other.allocAcctIdSource_) return false;
    if (hasAllocQty() != other.hasAllocQty()) return false;
    if (hasAllocQty()) {
      if (!getAllocQty()
          .equals(other.getAllocQty())) return false;
    }
    if (!getAllocSettlCurrency()
        .equals(other.getAllocSettlCurrency())) return false;
    if (!getIndividualAllocId()
        .equals(other.getIndividualAllocId())) return false;
    if (!getNestedParties3List()
        .equals(other.getNestedParties3List())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALLOC_ACCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAllocAccount().hashCode();
    hash = (37 * hash) + ALLOC_ACCT_ID_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + allocAcctIdSource_;
    if (hasAllocQty()) {
      hash = (37 * hash) + ALLOC_QTY_FIELD_NUMBER;
      hash = (53 * hash) + getAllocQty().hashCode();
    }
    hash = (37 * hash) + ALLOC_SETTL_CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getAllocSettlCurrency().hashCode();
    hash = (37 * hash) + INDIVIDUAL_ALLOC_ID_FIELD_NUMBER;
    hash = (53 * hash) + getIndividualAllocId().hashCode();
    if (getNestedParties3Count() > 0) {
      hash = (37 * hash) + NESTED_PARTIES3_FIELD_NUMBER;
      hash = (53 * hash) + getNestedParties3List().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.PreAllocMlegGrp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.fixprotocol.components.PreAllocMlegGrp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Common.PreAllocMlegGrp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Common.PreAllocMlegGrp)
      org.fixprotocol.components.PreAllocMlegGrpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fixprotocol.components.Common.internal_static_Common_PreAllocMlegGrp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fixprotocol.components.Common.internal_static_Common_PreAllocMlegGrp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fixprotocol.components.PreAllocMlegGrp.class, org.fixprotocol.components.PreAllocMlegGrp.Builder.class);
    }

    // Construct using org.fixprotocol.components.PreAllocMlegGrp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNestedParties3FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      allocAccount_ = "";

      allocAcctIdSource_ = 0;

      if (allocQtyBuilder_ == null) {
        allocQty_ = null;
      } else {
        allocQty_ = null;
        allocQtyBuilder_ = null;
      }
      allocSettlCurrency_ = "";

      individualAllocId_ = "";

      if (nestedParties3Builder_ == null) {
        nestedParties3_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nestedParties3Builder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.fixprotocol.components.Common.internal_static_Common_PreAllocMlegGrp_descriptor;
    }

    @java.lang.Override
    public org.fixprotocol.components.PreAllocMlegGrp getDefaultInstanceForType() {
      return org.fixprotocol.components.PreAllocMlegGrp.getDefaultInstance();
    }

    @java.lang.Override
    public org.fixprotocol.components.PreAllocMlegGrp build() {
      org.fixprotocol.components.PreAllocMlegGrp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.fixprotocol.components.PreAllocMlegGrp buildPartial() {
      org.fixprotocol.components.PreAllocMlegGrp result = new org.fixprotocol.components.PreAllocMlegGrp(this);
      int from_bitField0_ = bitField0_;
      result.allocAccount_ = allocAccount_;
      result.allocAcctIdSource_ = allocAcctIdSource_;
      if (allocQtyBuilder_ == null) {
        result.allocQty_ = allocQty_;
      } else {
        result.allocQty_ = allocQtyBuilder_.build();
      }
      result.allocSettlCurrency_ = allocSettlCurrency_;
      result.individualAllocId_ = individualAllocId_;
      if (nestedParties3Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          nestedParties3_ = java.util.Collections.unmodifiableList(nestedParties3_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.nestedParties3_ = nestedParties3_;
      } else {
        result.nestedParties3_ = nestedParties3Builder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.fixprotocol.components.PreAllocMlegGrp) {
        return mergeFrom((org.fixprotocol.components.PreAllocMlegGrp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.fixprotocol.components.PreAllocMlegGrp other) {
      if (other == org.fixprotocol.components.PreAllocMlegGrp.getDefaultInstance()) return this;
      if (!other.getAllocAccount().isEmpty()) {
        allocAccount_ = other.allocAccount_;
        onChanged();
      }
      if (other.allocAcctIdSource_ != 0) {
        setAllocAcctIdSourceValue(other.getAllocAcctIdSourceValue());
      }
      if (other.hasAllocQty()) {
        mergeAllocQty(other.getAllocQty());
      }
      if (!other.getAllocSettlCurrency().isEmpty()) {
        allocSettlCurrency_ = other.allocSettlCurrency_;
        onChanged();
      }
      if (!other.getIndividualAllocId().isEmpty()) {
        individualAllocId_ = other.individualAllocId_;
        onChanged();
      }
      if (nestedParties3Builder_ == null) {
        if (!other.nestedParties3_.isEmpty()) {
          if (nestedParties3_.isEmpty()) {
            nestedParties3_ = other.nestedParties3_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNestedParties3IsMutable();
            nestedParties3_.addAll(other.nestedParties3_);
          }
          onChanged();
        }
      } else {
        if (!other.nestedParties3_.isEmpty()) {
          if (nestedParties3Builder_.isEmpty()) {
            nestedParties3Builder_.dispose();
            nestedParties3Builder_ = null;
            nestedParties3_ = other.nestedParties3_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nestedParties3Builder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNestedParties3FieldBuilder() : null;
          } else {
            nestedParties3Builder_.addAllMessages(other.nestedParties3_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.fixprotocol.components.PreAllocMlegGrp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.fixprotocol.components.PreAllocMlegGrp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object allocAccount_ = "";
    /**
     * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.lang.String getAllocAccount() {
      java.lang.Object ref = allocAccount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allocAccount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public com.google.protobuf.ByteString
        getAllocAccountBytes() {
      java.lang.Object ref = allocAccount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allocAccount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocAccount(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      allocAccount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearAllocAccount() {
      
      allocAccount_ = getDefaultInstance().getAllocAccount();
      onChanged();
      return this;
    }
    /**
     * <code>string alloc_account = 1 [(.fix.tag) = 79, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocAccountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      allocAccount_ = value;
      onChanged();
      return this;
    }

    private int allocAcctIdSource_ = 0;
    /**
     * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public int getAllocAcctIdSourceValue() {
      return allocAcctIdSource_;
    }
    /**
     * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocAcctIdSourceValue(int value) {
      allocAcctIdSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.AllocAcctIDSourceEnum getAllocAcctIdSource() {
      @SuppressWarnings("deprecation")
      org.fixprotocol.components.AllocAcctIDSourceEnum result = org.fixprotocol.components.AllocAcctIDSourceEnum.valueOf(allocAcctIdSource_);
      return result == null ? org.fixprotocol.components.AllocAcctIDSourceEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocAcctIdSource(org.fixprotocol.components.AllocAcctIDSourceEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      allocAcctIdSource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Common.AllocAcctIDSourceEnum alloc_acct_id_source = 2 [(.fix.tag) = 661, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearAllocAcctIdSource() {
      
      allocAcctIdSource_ = 0;
      onChanged();
      return this;
    }

    private org.fixprotocol.components.Fix.Decimal64 allocQty_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fixprotocol.components.Fix.Decimal64, org.fixprotocol.components.Fix.Decimal64.Builder, org.fixprotocol.components.Fix.Decimal64OrBuilder> allocQtyBuilder_;
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public boolean hasAllocQty() {
      return allocQtyBuilder_ != null || allocQty_ != null;
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.Fix.Decimal64 getAllocQty() {
      if (allocQtyBuilder_ == null) {
        return allocQty_ == null ? org.fixprotocol.components.Fix.Decimal64.getDefaultInstance() : allocQty_;
      } else {
        return allocQtyBuilder_.getMessage();
      }
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocQty(org.fixprotocol.components.Fix.Decimal64 value) {
      if (allocQtyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        allocQty_ = value;
        onChanged();
      } else {
        allocQtyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocQty(
        org.fixprotocol.components.Fix.Decimal64.Builder builderForValue) {
      if (allocQtyBuilder_ == null) {
        allocQty_ = builderForValue.build();
        onChanged();
      } else {
        allocQtyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder mergeAllocQty(org.fixprotocol.components.Fix.Decimal64 value) {
      if (allocQtyBuilder_ == null) {
        if (allocQty_ != null) {
          allocQty_ =
            org.fixprotocol.components.Fix.Decimal64.newBuilder(allocQty_).mergeFrom(value).buildPartial();
        } else {
          allocQty_ = value;
        }
        onChanged();
      } else {
        allocQtyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearAllocQty() {
      if (allocQtyBuilder_ == null) {
        allocQty_ = null;
        onChanged();
      } else {
        allocQty_ = null;
        allocQtyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.Fix.Decimal64.Builder getAllocQtyBuilder() {
      
      onChanged();
      return getAllocQtyFieldBuilder().getBuilder();
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.Fix.Decimal64OrBuilder getAllocQtyOrBuilder() {
      if (allocQtyBuilder_ != null) {
        return allocQtyBuilder_.getMessageOrBuilder();
      } else {
        return allocQty_ == null ?
            org.fixprotocol.components.Fix.Decimal64.getDefaultInstance() : allocQty_;
      }
    }
    /**
     * <code>.fix.Decimal64 alloc_qty = 3 [(.fix.tag) = 80, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fixprotocol.components.Fix.Decimal64, org.fixprotocol.components.Fix.Decimal64.Builder, org.fixprotocol.components.Fix.Decimal64OrBuilder> 
        getAllocQtyFieldBuilder() {
      if (allocQtyBuilder_ == null) {
        allocQtyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.fixprotocol.components.Fix.Decimal64, org.fixprotocol.components.Fix.Decimal64.Builder, org.fixprotocol.components.Fix.Decimal64OrBuilder>(
                getAllocQty(),
                getParentForChildren(),
                isClean());
        allocQty_ = null;
      }
      return allocQtyBuilder_;
    }

    private java.lang.Object allocSettlCurrency_ = "";
    /**
     * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.lang.String getAllocSettlCurrency() {
      java.lang.Object ref = allocSettlCurrency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allocSettlCurrency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public com.google.protobuf.ByteString
        getAllocSettlCurrencyBytes() {
      java.lang.Object ref = allocSettlCurrency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allocSettlCurrency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocSettlCurrency(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      allocSettlCurrency_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearAllocSettlCurrency() {
      
      allocSettlCurrency_ = getDefaultInstance().getAllocSettlCurrency();
      onChanged();
      return this;
    }
    /**
     * <code>string alloc_settl_currency = 4 [(.fix.tag) = 736, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setAllocSettlCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      allocSettlCurrency_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object individualAllocId_ = "";
    /**
     * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.lang.String getIndividualAllocId() {
      java.lang.Object ref = individualAllocId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        individualAllocId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public com.google.protobuf.ByteString
        getIndividualAllocIdBytes() {
      java.lang.Object ref = individualAllocId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        individualAllocId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setIndividualAllocId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      individualAllocId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearIndividualAllocId() {
      
      individualAllocId_ = getDefaultInstance().getIndividualAllocId();
      onChanged();
      return this;
    }
    /**
     * <code>string individual_alloc_id = 5 [(.fix.tag) = 467, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setIndividualAllocIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      individualAllocId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.fixprotocol.components.NestedParties3> nestedParties3_ =
      java.util.Collections.emptyList();
    private void ensureNestedParties3IsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        nestedParties3_ = new java.util.ArrayList<org.fixprotocol.components.NestedParties3>(nestedParties3_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.fixprotocol.components.NestedParties3, org.fixprotocol.components.NestedParties3.Builder, org.fixprotocol.components.NestedParties3OrBuilder> nestedParties3Builder_;

    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.util.List<org.fixprotocol.components.NestedParties3> getNestedParties3List() {
      if (nestedParties3Builder_ == null) {
        return java.util.Collections.unmodifiableList(nestedParties3_);
      } else {
        return nestedParties3Builder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public int getNestedParties3Count() {
      if (nestedParties3Builder_ == null) {
        return nestedParties3_.size();
      } else {
        return nestedParties3Builder_.getCount();
      }
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.NestedParties3 getNestedParties3(int index) {
      if (nestedParties3Builder_ == null) {
        return nestedParties3_.get(index);
      } else {
        return nestedParties3Builder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setNestedParties3(
        int index, org.fixprotocol.components.NestedParties3 value) {
      if (nestedParties3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNestedParties3IsMutable();
        nestedParties3_.set(index, value);
        onChanged();
      } else {
        nestedParties3Builder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setNestedParties3(
        int index, org.fixprotocol.components.NestedParties3.Builder builderForValue) {
      if (nestedParties3Builder_ == null) {
        ensureNestedParties3IsMutable();
        nestedParties3_.set(index, builderForValue.build());
        onChanged();
      } else {
        nestedParties3Builder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addNestedParties3(org.fixprotocol.components.NestedParties3 value) {
      if (nestedParties3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNestedParties3IsMutable();
        nestedParties3_.add(value);
        onChanged();
      } else {
        nestedParties3Builder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addNestedParties3(
        int index, org.fixprotocol.components.NestedParties3 value) {
      if (nestedParties3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNestedParties3IsMutable();
        nestedParties3_.add(index, value);
        onChanged();
      } else {
        nestedParties3Builder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addNestedParties3(
        org.fixprotocol.components.NestedParties3.Builder builderForValue) {
      if (nestedParties3Builder_ == null) {
        ensureNestedParties3IsMutable();
        nestedParties3_.add(builderForValue.build());
        onChanged();
      } else {
        nestedParties3Builder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addNestedParties3(
        int index, org.fixprotocol.components.NestedParties3.Builder builderForValue) {
      if (nestedParties3Builder_ == null) {
        ensureNestedParties3IsMutable();
        nestedParties3_.add(index, builderForValue.build());
        onChanged();
      } else {
        nestedParties3Builder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addAllNestedParties3(
        java.lang.Iterable<? extends org.fixprotocol.components.NestedParties3> values) {
      if (nestedParties3Builder_ == null) {
        ensureNestedParties3IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, nestedParties3_);
        onChanged();
      } else {
        nestedParties3Builder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearNestedParties3() {
      if (nestedParties3Builder_ == null) {
        nestedParties3_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nestedParties3Builder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder removeNestedParties3(int index) {
      if (nestedParties3Builder_ == null) {
        ensureNestedParties3IsMutable();
        nestedParties3_.remove(index);
        onChanged();
      } else {
        nestedParties3Builder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.NestedParties3.Builder getNestedParties3Builder(
        int index) {
      return getNestedParties3FieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.NestedParties3OrBuilder getNestedParties3OrBuilder(
        int index) {
      if (nestedParties3Builder_ == null) {
        return nestedParties3_.get(index);  } else {
        return nestedParties3Builder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.util.List<? extends org.fixprotocol.components.NestedParties3OrBuilder> 
         getNestedParties3OrBuilderList() {
      if (nestedParties3Builder_ != null) {
        return nestedParties3Builder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(nestedParties3_);
      }
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.NestedParties3.Builder addNestedParties3Builder() {
      return getNestedParties3FieldBuilder().addBuilder(
          org.fixprotocol.components.NestedParties3.getDefaultInstance());
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.NestedParties3.Builder addNestedParties3Builder(
        int index) {
      return getNestedParties3FieldBuilder().addBuilder(
          index, org.fixprotocol.components.NestedParties3.getDefaultInstance());
    }
    /**
     * <code>repeated .Common.NestedParties3 nested_parties3 = 6 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.util.List<org.fixprotocol.components.NestedParties3.Builder> 
         getNestedParties3BuilderList() {
      return getNestedParties3FieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.fixprotocol.components.NestedParties3, org.fixprotocol.components.NestedParties3.Builder, org.fixprotocol.components.NestedParties3OrBuilder> 
        getNestedParties3FieldBuilder() {
      if (nestedParties3Builder_ == null) {
        nestedParties3Builder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.fixprotocol.components.NestedParties3, org.fixprotocol.components.NestedParties3.Builder, org.fixprotocol.components.NestedParties3OrBuilder>(
                nestedParties3_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        nestedParties3_ = null;
      }
      return nestedParties3Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Common.PreAllocMlegGrp)
  }

  // @@protoc_insertion_point(class_scope:Common.PreAllocMlegGrp)
  private static final org.fixprotocol.components.PreAllocMlegGrp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.fixprotocol.components.PreAllocMlegGrp();
  }

  public static org.fixprotocol.components.PreAllocMlegGrp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PreAllocMlegGrp>
      PARSER = new com.google.protobuf.AbstractParser<PreAllocMlegGrp>() {
    @java.lang.Override
    public PreAllocMlegGrp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PreAllocMlegGrp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PreAllocMlegGrp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreAllocMlegGrp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.fixprotocol.components.PreAllocMlegGrp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

