// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf enum {@code Common.PutOrCallEnum}
 */
public enum PutOrCallEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PUT_OR_CALL_UNSPECIFIED = 0;</code>
   */
  PUT_OR_CALL_UNSPECIFIED(0),
  /**
   * <code>PUT_OR_CALL_CALL = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_1];</code>
   */
  PUT_OR_CALL_CALL(1),
  /**
   * <code>PUT_OR_CALL_PUT = 2 [(.fix.enum_value) = "0", (.fix.enum_added) = VERSION_FIX_4_1];</code>
   */
  PUT_OR_CALL_PUT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PUT_OR_CALL_UNSPECIFIED = 0;</code>
   */
  public static final int PUT_OR_CALL_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PUT_OR_CALL_CALL = 1 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_1];</code>
   */
  public static final int PUT_OR_CALL_CALL_VALUE = 1;
  /**
   * <code>PUT_OR_CALL_PUT = 2 [(.fix.enum_value) = "0", (.fix.enum_added) = VERSION_FIX_4_1];</code>
   */
  public static final int PUT_OR_CALL_PUT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PutOrCallEnum valueOf(int value) {
    return forNumber(value);
  }

  public static PutOrCallEnum forNumber(int value) {
    switch (value) {
      case 0: return PUT_OR_CALL_UNSPECIFIED;
      case 1: return PUT_OR_CALL_CALL;
      case 2: return PUT_OR_CALL_PUT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PutOrCallEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PutOrCallEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PutOrCallEnum>() {
          public PutOrCallEnum findValueByNumber(int number) {
            return PutOrCallEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.getDescriptor().getEnumTypes().get(30);
  }

  private static final PutOrCallEnum[] VALUES = values();

  public static PutOrCallEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PutOrCallEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Common.PutOrCallEnum)
}

