// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf enum {@code Common.SettlPartyRoleEnum}
 */
public enum SettlPartyRoleEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SETTL_PARTY_ROLE_UNSPECIFIED = 0;</code>
   */
  SETTL_PARTY_ROLE_UNSPECIFIED(0),
  /**
   * <code>SETTL_PARTY_ROLE_BROKER_OF_CREDIT = 1 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_BROKER_OF_CREDIT(1),
  /**
   * <code>SETTL_PARTY_ROLE_CLEARING_FIRM = 2 [(.fix.enum_value) = "4", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_CLEARING_FIRM(2),
  /**
   * <code>SETTL_PARTY_ROLE_CLIENT_ID = 3 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_CLIENT_ID(3),
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_CLEARING_FIRM = 4 [(.fix.enum_value) = "18", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_CONTRA_CLEARING_FIRM(4),
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_FIRM = 5 [(.fix.enum_value) = "17", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_CONTRA_FIRM(5),
  /**
   * <code>SETTL_PARTY_ROLE_CORRESPONDANT_CLEARING_FIRM = 6 [(.fix.enum_value) = "15", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_CORRESPONDANT_CLEARING_FIRM(6),
  /**
   * <code>SETTL_PARTY_ROLE_ENTERING_FIRM = 7 [(.fix.enum_value) = "7", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_ENTERING_FIRM(7),
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_FIRM = 8 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_EXECUTING_FIRM(8),
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_SYSTEM = 9 [(.fix.enum_value) = "16", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_EXECUTING_SYSTEM(9),
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_TRADER = 10 [(.fix.enum_value) = "12", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_EXECUTING_TRADER(10),
  /**
   * <code>SETTL_PARTY_ROLE_FUND_MANAGER_CLIENT_ID = 11 [(.fix.enum_value) = "9", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_FUND_MANAGER_CLIENT_ID(11),
  /**
   * <code>SETTL_PARTY_ROLE_GIVEUP_CLEARING_FIRM = 12 [(.fix.enum_value) = "14", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_GIVEUP_CLEARING_FIRM(12),
  /**
   * <code>SETTL_PARTY_ROLE_INTRODUCING_FIRM = 13 [(.fix.enum_value) = "6", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_INTRODUCING_FIRM(13),
  /**
   * <code>SETTL_PARTY_ROLE_INVESTOR_ID = 14 [(.fix.enum_value) = "5", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_INVESTOR_ID(14),
  /**
   * <code>SETTL_PARTY_ROLE_LOCATE = 15 [(.fix.enum_value) = "8", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_LOCATE(15),
  /**
   * <code>SETTL_PARTY_ROLE_ORDER_ORIGINATION_FIRM = 16 [(.fix.enum_value) = "13", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_ORDER_ORIGINATION_FIRM(16),
  /**
   * <code>SETTL_PARTY_ROLE_ORDER_ORIGINATION_TRADER = 17 [(.fix.enum_value) = "11", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_ORDER_ORIGINATION_TRADER(17),
  /**
   * <code>SETTL_PARTY_ROLE_SETTLEMENT_LOCATION = 18 [(.fix.enum_value) = "10", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_SETTLEMENT_LOCATION(18),
  /**
   * <code>SETTL_PARTY_ROLE_SPONSORING_FIRM = 19 [(.fix.enum_value) = "19", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_SPONSORING_FIRM(19),
  /**
   * <code>SETTL_PARTY_ROLE_UNDERLYING_CONTRA_FIRM = 20 [(.fix.enum_value) = "20", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  SETTL_PARTY_ROLE_UNDERLYING_CONTRA_FIRM(20),
  /**
   * <code>SETTL_PARTY_ROLE_AGENT = 21 [(.fix.enum_value) = "30", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_AGENT(21),
  /**
   * <code>SETTL_PARTY_ROLE_BENEFICIARY = 22 [(.fix.enum_value) = "32", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_BENEFICIARY(22),
  /**
   * <code>SETTL_PARTY_ROLE_BUYER = 23 [(.fix.enum_value) = "27", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_BUYER(23),
  /**
   * <code>SETTL_PARTY_ROLE_CLEARING_ORGANIZATION = 24 [(.fix.enum_value) = "21", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CLEARING_ORGANIZATION(24),
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_INVESTOR_ID = 25 [(.fix.enum_value) = "39", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CONTRA_INVESTOR_ID(25),
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_TRADER = 26 [(.fix.enum_value) = "37", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CONTRA_TRADER(26),
  /**
   * <code>SETTL_PARTY_ROLE_CORRESPONDENT_BROKER = 27 [(.fix.enum_value) = "26", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CORRESPONDENT_BROKER(27),
  /**
   * <code>SETTL_PARTY_ROLE_CORRESPONDENT_CLEARING_ORGANIZATION = 28 [(.fix.enum_value) = "25", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CORRESPONDENT_CLEARING_ORGANIZATION(28),
  /**
   * <code>SETTL_PARTY_ROLE_CUSTODIAN = 29 [(.fix.enum_value) = "28", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CUSTODIAN(29),
  /**
   * <code>SETTL_PARTY_ROLE_CUSTOMER_ACCOUNT = 30 [(.fix.enum_value) = "24", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_CUSTOMER_ACCOUNT(30),
  /**
   * <code>SETTL_PARTY_ROLE_ENTERING_TRADER = 31 [(.fix.enum_value) = "36", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_ENTERING_TRADER(31),
  /**
   * <code>SETTL_PARTY_ROLE_EXCHANGE = 32 [(.fix.enum_value) = "22", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_EXCHANGE(32),
  /**
   * <code>SETTL_PARTY_ROLE_INTERESTED_PARTY = 33 [(.fix.enum_value) = "33", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_INTERESTED_PARTY(33),
  /**
   * <code>SETTL_PARTY_ROLE_INTERMEDIARY = 34 [(.fix.enum_value) = "29", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_INTERMEDIARY(34),
  /**
   * <code>SETTL_PARTY_ROLE_LIQUIDITY_PROVIDER = 35 [(.fix.enum_value) = "35", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_LIQUIDITY_PROVIDER(35),
  /**
   * <code>SETTL_PARTY_ROLE_POSITION_ACCOUNT = 36 [(.fix.enum_value) = "38", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_POSITION_ACCOUNT(36),
  /**
   * <code>SETTL_PARTY_ROLE_REGULATORY_BODY = 37 [(.fix.enum_value) = "34", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_REGULATORY_BODY(37),
  /**
   * <code>SETTL_PARTY_ROLE_SUB_CUSTODIAN = 38 [(.fix.enum_value) = "31", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_SUB_CUSTODIAN(38),
  /**
   * <code>SETTL_PARTY_ROLE_TRANSFER_TO_FIRM = 39 [(.fix.enum_value) = "40", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  SETTL_PARTY_ROLE_TRANSFER_TO_FIRM(39),
  /**
   * <code>SETTL_PARTY_ROLE_INTRODUCING_BROKER = 40 [(.fix.enum_value) = "60", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 4];</code>
   */
  SETTL_PARTY_ROLE_INTRODUCING_BROKER(40),
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_EXCHANGE = 41 [(.fix.enum_value) = "42", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  SETTL_PARTY_ROLE_CONTRA_EXCHANGE(41),
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_POSITION_ACCOUNT = 42 [(.fix.enum_value) = "41", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  SETTL_PARTY_ROLE_CONTRA_POSITION_ACCOUNT(42),
  /**
   * <code>SETTL_PARTY_ROLE_INTERNAL_CARRY_ACCOUNT = 43 [(.fix.enum_value) = "43", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  SETTL_PARTY_ROLE_INTERNAL_CARRY_ACCOUNT(43),
  /**
   * <code>SETTL_PARTY_ROLE_ORDER_ENTRY_OPERATOR_ID = 44 [(.fix.enum_value) = "44", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  SETTL_PARTY_ROLE_ORDER_ENTRY_OPERATOR_ID(44),
  /**
   * <code>SETTL_PARTY_ROLE_SECONDARY_ACCOUNT_NUMBER = 45 [(.fix.enum_value) = "45", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  SETTL_PARTY_ROLE_SECONDARY_ACCOUNT_NUMBER(45),
  /**
   * <code>SETTL_PARTY_ROLE_ASSET_MANAGER = 46 [(.fix.enum_value) = "49", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_ASSET_MANAGER(46),
  /**
   * <code>SETTL_PARTY_ROLE_CLAIMING_ACCOUNT = 47 [(.fix.enum_value) = "48", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_CLAIMING_ACCOUNT(47),
  /**
   * <code>SETTL_PARTY_ROLE_FOREIGN_FIRM = 48 [(.fix.enum_value) = "46", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_FOREIGN_FIRM(48),
  /**
   * <code>SETTL_PARTY_ROLE_LARGE_TRADER_REPORTABLE_ACCOUNT = 49 [(.fix.enum_value) = "52", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_LARGE_TRADER_REPORTABLE_ACCOUNT(49),
  /**
   * <code>SETTL_PARTY_ROLE_PLEDGEE_ACCOUNT = 50 [(.fix.enum_value) = "51", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_PLEDGEE_ACCOUNT(50),
  /**
   * <code>SETTL_PARTY_ROLE_PLEDGOR_ACCOUNT = 51 [(.fix.enum_value) = "50", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_PLEDGOR_ACCOUNT(51),
  /**
   * <code>SETTL_PARTY_ROLE_SENDER_LOCATION = 52 [(.fix.enum_value) = "54", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_SENDER_LOCATION(52),
  /**
   * <code>SETTL_PARTY_ROLE_SESSION_ID = 53 [(.fix.enum_value) = "55", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_SESSION_ID(53),
  /**
   * <code>SETTL_PARTY_ROLE_THIRD_PARTY_ALLOCATION_FIRM = 54 [(.fix.enum_value) = "47", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_THIRD_PARTY_ALLOCATION_FIRM(54),
  /**
   * <code>SETTL_PARTY_ROLE_TRADER_MNEMONIC = 55 [(.fix.enum_value) = "53", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  SETTL_PARTY_ROLE_TRADER_MNEMONIC(55),
  /**
   * <code>SETTL_PARTY_ROLE_ACCEPTABLE_COUNTERPARTY = 56 [(.fix.enum_value) = "56", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  SETTL_PARTY_ROLE_ACCEPTABLE_COUNTERPARTY(56),
  /**
   * <code>SETTL_PARTY_ROLE_ENTERING_UNIT = 57 [(.fix.enum_value) = "58", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  SETTL_PARTY_ROLE_ENTERING_UNIT(57),
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_UNIT = 58 [(.fix.enum_value) = "59", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  SETTL_PARTY_ROLE_EXECUTING_UNIT(58),
  /**
   * <code>SETTL_PARTY_ROLE_UNACCEPTABLE_COUNTERPARTY = 59 [(.fix.enum_value) = "57", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  SETTL_PARTY_ROLE_UNACCEPTABLE_COUNTERPARTY(59),
  /**
   * <code>SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_LIQUIDITY = 60 [(.fix.enum_value) = "70", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_LIQUIDITY(60),
  /**
   * <code>SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_TRANSACTION_VENUE = 61 [(.fix.enum_value) = "71", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_TRANSACTION_VENUE(61),
  /**
   * <code>SETTL_PARTY_ROLE_DESK_ID = 62 [(.fix.enum_value) = "76", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_DESK_ID(62),
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTION_VENUE = 63 [(.fix.enum_value) = "73", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_EXECUTION_VENUE(63),
  /**
   * <code>SETTL_PARTY_ROLE_HOME_COMPETENT_AUTHORITY = 64 [(.fix.enum_value) = "69", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_HOME_COMPETENT_AUTHORITY(64),
  /**
   * <code>SETTL_PARTY_ROLE_HOST_COMPETENT_AUTHORITY = 65 [(.fix.enum_value) = "68", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_HOST_COMPETENT_AUTHORITY(65),
  /**
   * <code>SETTL_PARTY_ROLE_INVESTMENT_FIRM = 66 [(.fix.enum_value) = "67", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_INVESTMENT_FIRM(66),
  /**
   * <code>SETTL_PARTY_ROLE_LOCATION_ID = 67 [(.fix.enum_value) = "75", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_LOCATION_ID(67),
  /**
   * <code>SETTL_PARTY_ROLE_MARKET_DATA_ENTRY_ORIGINATOR = 68 [(.fix.enum_value) = "74", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_MARKET_DATA_ENTRY_ORIGINATOR(68),
  /**
   * <code>SETTL_PARTY_ROLE_MARKET_DATA_MARKET = 69 [(.fix.enum_value) = "77", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_MARKET_DATA_MARKET(69),
  /**
   * <code>SETTL_PARTY_ROLE_MARKET_MAKER = 70 [(.fix.enum_value) = "66", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_MARKET_MAKER(70),
  /**
   * <code>SETTL_PARTY_ROLE_MULTILATERAL_TRADING_FACILITY = 71 [(.fix.enum_value) = "64", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_MULTILATERAL_TRADING_FACILITY(71),
  /**
   * <code>SETTL_PARTY_ROLE_QUOTE_ORIGINATOR = 72 [(.fix.enum_value) = "61", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_QUOTE_ORIGINATOR(72),
  /**
   * <code>SETTL_PARTY_ROLE_REGULATED_MARKET = 73 [(.fix.enum_value) = "65", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_REGULATED_MARKET(73),
  /**
   * <code>SETTL_PARTY_ROLE_REPORTING_INTERMEDIARY = 74 [(.fix.enum_value) = "72", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_REPORTING_INTERMEDIARY(74),
  /**
   * <code>SETTL_PARTY_ROLE_REPORT_ORIGINATOR = 75 [(.fix.enum_value) = "62", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_REPORT_ORIGINATOR(75),
  /**
   * <code>SETTL_PARTY_ROLE_SYSTEMATIC_INTERNALISER = 76 [(.fix.enum_value) = "63", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  SETTL_PARTY_ROLE_SYSTEMATIC_INTERNALISER(76),
  /**
   * <code>SETTL_PARTY_ROLE_ALLOCATION_ENTITY = 77 [(.fix.enum_value) = "78", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 35];</code>
   */
  SETTL_PARTY_ROLE_ALLOCATION_ENTITY(77),
  /**
   * <code>SETTL_PARTY_ROLE_BROKER_CLEARING_ID = 78 [(.fix.enum_value) = "81", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 68];</code>
   */
  SETTL_PARTY_ROLE_BROKER_CLEARING_ID(78),
  /**
   * <code>SETTL_PARTY_ROLE_PRIME_BROKER = 79 [(.fix.enum_value) = "79", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 68];</code>
   */
  SETTL_PARTY_ROLE_PRIME_BROKER(79),
  /**
   * <code>SETTL_PARTY_ROLE_STEP_OUT_FIRM = 80 [(.fix.enum_value) = "80", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 68];</code>
   */
  SETTL_PARTY_ROLE_STEP_OUT_FIRM(80),
  /**
   * <code>SETTL_PARTY_ROLE_CENTRAL_REGISTRATION_DEPOSITORY = 81 [(.fix.enum_value) = "82", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 79];</code>
   */
  SETTL_PARTY_ROLE_CENTRAL_REGISTRATION_DEPOSITORY(81),
  /**
   * <code>SETTL_PARTY_ROLE_ACCEPTABLE_SETTLING_COUNTERPARTY = 82 [(.fix.enum_value) = "84", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 96];</code>
   */
  SETTL_PARTY_ROLE_ACCEPTABLE_SETTLING_COUNTERPARTY(82),
  /**
   * <code>SETTL_PARTY_ROLE_CLEARING_ACCOUNT = 83 [(.fix.enum_value) = "83", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 96];</code>
   */
  SETTL_PARTY_ROLE_CLEARING_ACCOUNT(83),
  /**
   * <code>SETTL_PARTY_ROLE_UNACCEPTABLE_SETTLING_COUNTERPARTY = 84 [(.fix.enum_value) = "85", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 96];</code>
   */
  SETTL_PARTY_ROLE_UNACCEPTABLE_SETTLING_COUNTERPARTY(84),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SETTL_PARTY_ROLE_UNSPECIFIED = 0;</code>
   */
  public static final int SETTL_PARTY_ROLE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SETTL_PARTY_ROLE_BROKER_OF_CREDIT = 1 [(.fix.enum_value) = "2", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_BROKER_OF_CREDIT_VALUE = 1;
  /**
   * <code>SETTL_PARTY_ROLE_CLEARING_FIRM = 2 [(.fix.enum_value) = "4", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_CLEARING_FIRM_VALUE = 2;
  /**
   * <code>SETTL_PARTY_ROLE_CLIENT_ID = 3 [(.fix.enum_value) = "3", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_CLIENT_ID_VALUE = 3;
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_CLEARING_FIRM = 4 [(.fix.enum_value) = "18", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_CONTRA_CLEARING_FIRM_VALUE = 4;
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_FIRM = 5 [(.fix.enum_value) = "17", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_CONTRA_FIRM_VALUE = 5;
  /**
   * <code>SETTL_PARTY_ROLE_CORRESPONDANT_CLEARING_FIRM = 6 [(.fix.enum_value) = "15", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_CORRESPONDANT_CLEARING_FIRM_VALUE = 6;
  /**
   * <code>SETTL_PARTY_ROLE_ENTERING_FIRM = 7 [(.fix.enum_value) = "7", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_ENTERING_FIRM_VALUE = 7;
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_FIRM = 8 [(.fix.enum_value) = "1", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_EXECUTING_FIRM_VALUE = 8;
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_SYSTEM = 9 [(.fix.enum_value) = "16", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_EXECUTING_SYSTEM_VALUE = 9;
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_TRADER = 10 [(.fix.enum_value) = "12", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_EXECUTING_TRADER_VALUE = 10;
  /**
   * <code>SETTL_PARTY_ROLE_FUND_MANAGER_CLIENT_ID = 11 [(.fix.enum_value) = "9", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_FUND_MANAGER_CLIENT_ID_VALUE = 11;
  /**
   * <code>SETTL_PARTY_ROLE_GIVEUP_CLEARING_FIRM = 12 [(.fix.enum_value) = "14", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_GIVEUP_CLEARING_FIRM_VALUE = 12;
  /**
   * <code>SETTL_PARTY_ROLE_INTRODUCING_FIRM = 13 [(.fix.enum_value) = "6", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_INTRODUCING_FIRM_VALUE = 13;
  /**
   * <code>SETTL_PARTY_ROLE_INVESTOR_ID = 14 [(.fix.enum_value) = "5", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_INVESTOR_ID_VALUE = 14;
  /**
   * <code>SETTL_PARTY_ROLE_LOCATE = 15 [(.fix.enum_value) = "8", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_LOCATE_VALUE = 15;
  /**
   * <code>SETTL_PARTY_ROLE_ORDER_ORIGINATION_FIRM = 16 [(.fix.enum_value) = "13", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_ORDER_ORIGINATION_FIRM_VALUE = 16;
  /**
   * <code>SETTL_PARTY_ROLE_ORDER_ORIGINATION_TRADER = 17 [(.fix.enum_value) = "11", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_ORDER_ORIGINATION_TRADER_VALUE = 17;
  /**
   * <code>SETTL_PARTY_ROLE_SETTLEMENT_LOCATION = 18 [(.fix.enum_value) = "10", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_SETTLEMENT_LOCATION_VALUE = 18;
  /**
   * <code>SETTL_PARTY_ROLE_SPONSORING_FIRM = 19 [(.fix.enum_value) = "19", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_SPONSORING_FIRM_VALUE = 19;
  /**
   * <code>SETTL_PARTY_ROLE_UNDERLYING_CONTRA_FIRM = 20 [(.fix.enum_value) = "20", (.fix.enum_added) = VERSION_FIX_4_3];</code>
   */
  public static final int SETTL_PARTY_ROLE_UNDERLYING_CONTRA_FIRM_VALUE = 20;
  /**
   * <code>SETTL_PARTY_ROLE_AGENT = 21 [(.fix.enum_value) = "30", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_AGENT_VALUE = 21;
  /**
   * <code>SETTL_PARTY_ROLE_BENEFICIARY = 22 [(.fix.enum_value) = "32", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_BENEFICIARY_VALUE = 22;
  /**
   * <code>SETTL_PARTY_ROLE_BUYER = 23 [(.fix.enum_value) = "27", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_BUYER_VALUE = 23;
  /**
   * <code>SETTL_PARTY_ROLE_CLEARING_ORGANIZATION = 24 [(.fix.enum_value) = "21", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CLEARING_ORGANIZATION_VALUE = 24;
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_INVESTOR_ID = 25 [(.fix.enum_value) = "39", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CONTRA_INVESTOR_ID_VALUE = 25;
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_TRADER = 26 [(.fix.enum_value) = "37", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CONTRA_TRADER_VALUE = 26;
  /**
   * <code>SETTL_PARTY_ROLE_CORRESPONDENT_BROKER = 27 [(.fix.enum_value) = "26", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CORRESPONDENT_BROKER_VALUE = 27;
  /**
   * <code>SETTL_PARTY_ROLE_CORRESPONDENT_CLEARING_ORGANIZATION = 28 [(.fix.enum_value) = "25", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CORRESPONDENT_CLEARING_ORGANIZATION_VALUE = 28;
  /**
   * <code>SETTL_PARTY_ROLE_CUSTODIAN = 29 [(.fix.enum_value) = "28", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CUSTODIAN_VALUE = 29;
  /**
   * <code>SETTL_PARTY_ROLE_CUSTOMER_ACCOUNT = 30 [(.fix.enum_value) = "24", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_CUSTOMER_ACCOUNT_VALUE = 30;
  /**
   * <code>SETTL_PARTY_ROLE_ENTERING_TRADER = 31 [(.fix.enum_value) = "36", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_ENTERING_TRADER_VALUE = 31;
  /**
   * <code>SETTL_PARTY_ROLE_EXCHANGE = 32 [(.fix.enum_value) = "22", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_EXCHANGE_VALUE = 32;
  /**
   * <code>SETTL_PARTY_ROLE_INTERESTED_PARTY = 33 [(.fix.enum_value) = "33", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_INTERESTED_PARTY_VALUE = 33;
  /**
   * <code>SETTL_PARTY_ROLE_INTERMEDIARY = 34 [(.fix.enum_value) = "29", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_INTERMEDIARY_VALUE = 34;
  /**
   * <code>SETTL_PARTY_ROLE_LIQUIDITY_PROVIDER = 35 [(.fix.enum_value) = "35", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_LIQUIDITY_PROVIDER_VALUE = 35;
  /**
   * <code>SETTL_PARTY_ROLE_POSITION_ACCOUNT = 36 [(.fix.enum_value) = "38", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_POSITION_ACCOUNT_VALUE = 36;
  /**
   * <code>SETTL_PARTY_ROLE_REGULATORY_BODY = 37 [(.fix.enum_value) = "34", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_REGULATORY_BODY_VALUE = 37;
  /**
   * <code>SETTL_PARTY_ROLE_SUB_CUSTODIAN = 38 [(.fix.enum_value) = "31", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_SUB_CUSTODIAN_VALUE = 38;
  /**
   * <code>SETTL_PARTY_ROLE_TRANSFER_TO_FIRM = 39 [(.fix.enum_value) = "40", (.fix.enum_added) = VERSION_FIX_4_4];</code>
   */
  public static final int SETTL_PARTY_ROLE_TRANSFER_TO_FIRM_VALUE = 39;
  /**
   * <code>SETTL_PARTY_ROLE_INTRODUCING_BROKER = 40 [(.fix.enum_value) = "60", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 4];</code>
   */
  public static final int SETTL_PARTY_ROLE_INTRODUCING_BROKER_VALUE = 40;
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_EXCHANGE = 41 [(.fix.enum_value) = "42", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  public static final int SETTL_PARTY_ROLE_CONTRA_EXCHANGE_VALUE = 41;
  /**
   * <code>SETTL_PARTY_ROLE_CONTRA_POSITION_ACCOUNT = 42 [(.fix.enum_value) = "41", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  public static final int SETTL_PARTY_ROLE_CONTRA_POSITION_ACCOUNT_VALUE = 42;
  /**
   * <code>SETTL_PARTY_ROLE_INTERNAL_CARRY_ACCOUNT = 43 [(.fix.enum_value) = "43", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  public static final int SETTL_PARTY_ROLE_INTERNAL_CARRY_ACCOUNT_VALUE = 43;
  /**
   * <code>SETTL_PARTY_ROLE_ORDER_ENTRY_OPERATOR_ID = 44 [(.fix.enum_value) = "44", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  public static final int SETTL_PARTY_ROLE_ORDER_ENTRY_OPERATOR_ID_VALUE = 44;
  /**
   * <code>SETTL_PARTY_ROLE_SECONDARY_ACCOUNT_NUMBER = 45 [(.fix.enum_value) = "45", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 5];</code>
   */
  public static final int SETTL_PARTY_ROLE_SECONDARY_ACCOUNT_NUMBER_VALUE = 45;
  /**
   * <code>SETTL_PARTY_ROLE_ASSET_MANAGER = 46 [(.fix.enum_value) = "49", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_ASSET_MANAGER_VALUE = 46;
  /**
   * <code>SETTL_PARTY_ROLE_CLAIMING_ACCOUNT = 47 [(.fix.enum_value) = "48", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_CLAIMING_ACCOUNT_VALUE = 47;
  /**
   * <code>SETTL_PARTY_ROLE_FOREIGN_FIRM = 48 [(.fix.enum_value) = "46", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_FOREIGN_FIRM_VALUE = 48;
  /**
   * <code>SETTL_PARTY_ROLE_LARGE_TRADER_REPORTABLE_ACCOUNT = 49 [(.fix.enum_value) = "52", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_LARGE_TRADER_REPORTABLE_ACCOUNT_VALUE = 49;
  /**
   * <code>SETTL_PARTY_ROLE_PLEDGEE_ACCOUNT = 50 [(.fix.enum_value) = "51", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_PLEDGEE_ACCOUNT_VALUE = 50;
  /**
   * <code>SETTL_PARTY_ROLE_PLEDGOR_ACCOUNT = 51 [(.fix.enum_value) = "50", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_PLEDGOR_ACCOUNT_VALUE = 51;
  /**
   * <code>SETTL_PARTY_ROLE_SENDER_LOCATION = 52 [(.fix.enum_value) = "54", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_SENDER_LOCATION_VALUE = 52;
  /**
   * <code>SETTL_PARTY_ROLE_SESSION_ID = 53 [(.fix.enum_value) = "55", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_SESSION_ID_VALUE = 53;
  /**
   * <code>SETTL_PARTY_ROLE_THIRD_PARTY_ALLOCATION_FIRM = 54 [(.fix.enum_value) = "47", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_THIRD_PARTY_ALLOCATION_FIRM_VALUE = 54;
  /**
   * <code>SETTL_PARTY_ROLE_TRADER_MNEMONIC = 55 [(.fix.enum_value) = "53", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 8];</code>
   */
  public static final int SETTL_PARTY_ROLE_TRADER_MNEMONIC_VALUE = 55;
  /**
   * <code>SETTL_PARTY_ROLE_ACCEPTABLE_COUNTERPARTY = 56 [(.fix.enum_value) = "56", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  public static final int SETTL_PARTY_ROLE_ACCEPTABLE_COUNTERPARTY_VALUE = 56;
  /**
   * <code>SETTL_PARTY_ROLE_ENTERING_UNIT = 57 [(.fix.enum_value) = "58", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  public static final int SETTL_PARTY_ROLE_ENTERING_UNIT_VALUE = 57;
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTING_UNIT = 58 [(.fix.enum_value) = "59", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  public static final int SETTL_PARTY_ROLE_EXECUTING_UNIT_VALUE = 58;
  /**
   * <code>SETTL_PARTY_ROLE_UNACCEPTABLE_COUNTERPARTY = 59 [(.fix.enum_value) = "57", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 22];</code>
   */
  public static final int SETTL_PARTY_ROLE_UNACCEPTABLE_COUNTERPARTY_VALUE = 59;
  /**
   * <code>SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_LIQUIDITY = 60 [(.fix.enum_value) = "70", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_LIQUIDITY_VALUE = 60;
  /**
   * <code>SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_TRANSACTION_VENUE = 61 [(.fix.enum_value) = "71", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_TRANSACTION_VENUE_VALUE = 61;
  /**
   * <code>SETTL_PARTY_ROLE_DESK_ID = 62 [(.fix.enum_value) = "76", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_DESK_ID_VALUE = 62;
  /**
   * <code>SETTL_PARTY_ROLE_EXECUTION_VENUE = 63 [(.fix.enum_value) = "73", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_EXECUTION_VENUE_VALUE = 63;
  /**
   * <code>SETTL_PARTY_ROLE_HOME_COMPETENT_AUTHORITY = 64 [(.fix.enum_value) = "69", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_HOME_COMPETENT_AUTHORITY_VALUE = 64;
  /**
   * <code>SETTL_PARTY_ROLE_HOST_COMPETENT_AUTHORITY = 65 [(.fix.enum_value) = "68", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_HOST_COMPETENT_AUTHORITY_VALUE = 65;
  /**
   * <code>SETTL_PARTY_ROLE_INVESTMENT_FIRM = 66 [(.fix.enum_value) = "67", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_INVESTMENT_FIRM_VALUE = 66;
  /**
   * <code>SETTL_PARTY_ROLE_LOCATION_ID = 67 [(.fix.enum_value) = "75", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_LOCATION_ID_VALUE = 67;
  /**
   * <code>SETTL_PARTY_ROLE_MARKET_DATA_ENTRY_ORIGINATOR = 68 [(.fix.enum_value) = "74", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_MARKET_DATA_ENTRY_ORIGINATOR_VALUE = 68;
  /**
   * <code>SETTL_PARTY_ROLE_MARKET_DATA_MARKET = 69 [(.fix.enum_value) = "77", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_MARKET_DATA_MARKET_VALUE = 69;
  /**
   * <code>SETTL_PARTY_ROLE_MARKET_MAKER = 70 [(.fix.enum_value) = "66", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_MARKET_MAKER_VALUE = 70;
  /**
   * <code>SETTL_PARTY_ROLE_MULTILATERAL_TRADING_FACILITY = 71 [(.fix.enum_value) = "64", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_MULTILATERAL_TRADING_FACILITY_VALUE = 71;
  /**
   * <code>SETTL_PARTY_ROLE_QUOTE_ORIGINATOR = 72 [(.fix.enum_value) = "61", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_QUOTE_ORIGINATOR_VALUE = 72;
  /**
   * <code>SETTL_PARTY_ROLE_REGULATED_MARKET = 73 [(.fix.enum_value) = "65", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_REGULATED_MARKET_VALUE = 73;
  /**
   * <code>SETTL_PARTY_ROLE_REPORTING_INTERMEDIARY = 74 [(.fix.enum_value) = "72", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_REPORTING_INTERMEDIARY_VALUE = 74;
  /**
   * <code>SETTL_PARTY_ROLE_REPORT_ORIGINATOR = 75 [(.fix.enum_value) = "62", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_REPORT_ORIGINATOR_VALUE = 75;
  /**
   * <code>SETTL_PARTY_ROLE_SYSTEMATIC_INTERNALISER = 76 [(.fix.enum_value) = "63", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 26];</code>
   */
  public static final int SETTL_PARTY_ROLE_SYSTEMATIC_INTERNALISER_VALUE = 76;
  /**
   * <code>SETTL_PARTY_ROLE_ALLOCATION_ENTITY = 77 [(.fix.enum_value) = "78", (.fix.enum_added) = VERSION_FIX_4_4, (.fix.enum_added_ep) = 35];</code>
   */
  public static final int SETTL_PARTY_ROLE_ALLOCATION_ENTITY_VALUE = 77;
  /**
   * <code>SETTL_PARTY_ROLE_BROKER_CLEARING_ID = 78 [(.fix.enum_value) = "81", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 68];</code>
   */
  public static final int SETTL_PARTY_ROLE_BROKER_CLEARING_ID_VALUE = 78;
  /**
   * <code>SETTL_PARTY_ROLE_PRIME_BROKER = 79 [(.fix.enum_value) = "79", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 68];</code>
   */
  public static final int SETTL_PARTY_ROLE_PRIME_BROKER_VALUE = 79;
  /**
   * <code>SETTL_PARTY_ROLE_STEP_OUT_FIRM = 80 [(.fix.enum_value) = "80", (.fix.enum_added) = VERSION_FIX_5_0, (.fix.enum_added_ep) = 68];</code>
   */
  public static final int SETTL_PARTY_ROLE_STEP_OUT_FIRM_VALUE = 80;
  /**
   * <code>SETTL_PARTY_ROLE_CENTRAL_REGISTRATION_DEPOSITORY = 81 [(.fix.enum_value) = "82", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 79];</code>
   */
  public static final int SETTL_PARTY_ROLE_CENTRAL_REGISTRATION_DEPOSITORY_VALUE = 81;
  /**
   * <code>SETTL_PARTY_ROLE_ACCEPTABLE_SETTLING_COUNTERPARTY = 82 [(.fix.enum_value) = "84", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 96];</code>
   */
  public static final int SETTL_PARTY_ROLE_ACCEPTABLE_SETTLING_COUNTERPARTY_VALUE = 82;
  /**
   * <code>SETTL_PARTY_ROLE_CLEARING_ACCOUNT = 83 [(.fix.enum_value) = "83", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 96];</code>
   */
  public static final int SETTL_PARTY_ROLE_CLEARING_ACCOUNT_VALUE = 83;
  /**
   * <code>SETTL_PARTY_ROLE_UNACCEPTABLE_SETTLING_COUNTERPARTY = 84 [(.fix.enum_value) = "85", (.fix.enum_added) = VERSION_FIX_5_0SP1, (.fix.enum_added_ep) = 96];</code>
   */
  public static final int SETTL_PARTY_ROLE_UNACCEPTABLE_SETTLING_COUNTERPARTY_VALUE = 84;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SettlPartyRoleEnum valueOf(int value) {
    return forNumber(value);
  }

  public static SettlPartyRoleEnum forNumber(int value) {
    switch (value) {
      case 0: return SETTL_PARTY_ROLE_UNSPECIFIED;
      case 1: return SETTL_PARTY_ROLE_BROKER_OF_CREDIT;
      case 2: return SETTL_PARTY_ROLE_CLEARING_FIRM;
      case 3: return SETTL_PARTY_ROLE_CLIENT_ID;
      case 4: return SETTL_PARTY_ROLE_CONTRA_CLEARING_FIRM;
      case 5: return SETTL_PARTY_ROLE_CONTRA_FIRM;
      case 6: return SETTL_PARTY_ROLE_CORRESPONDANT_CLEARING_FIRM;
      case 7: return SETTL_PARTY_ROLE_ENTERING_FIRM;
      case 8: return SETTL_PARTY_ROLE_EXECUTING_FIRM;
      case 9: return SETTL_PARTY_ROLE_EXECUTING_SYSTEM;
      case 10: return SETTL_PARTY_ROLE_EXECUTING_TRADER;
      case 11: return SETTL_PARTY_ROLE_FUND_MANAGER_CLIENT_ID;
      case 12: return SETTL_PARTY_ROLE_GIVEUP_CLEARING_FIRM;
      case 13: return SETTL_PARTY_ROLE_INTRODUCING_FIRM;
      case 14: return SETTL_PARTY_ROLE_INVESTOR_ID;
      case 15: return SETTL_PARTY_ROLE_LOCATE;
      case 16: return SETTL_PARTY_ROLE_ORDER_ORIGINATION_FIRM;
      case 17: return SETTL_PARTY_ROLE_ORDER_ORIGINATION_TRADER;
      case 18: return SETTL_PARTY_ROLE_SETTLEMENT_LOCATION;
      case 19: return SETTL_PARTY_ROLE_SPONSORING_FIRM;
      case 20: return SETTL_PARTY_ROLE_UNDERLYING_CONTRA_FIRM;
      case 21: return SETTL_PARTY_ROLE_AGENT;
      case 22: return SETTL_PARTY_ROLE_BENEFICIARY;
      case 23: return SETTL_PARTY_ROLE_BUYER;
      case 24: return SETTL_PARTY_ROLE_CLEARING_ORGANIZATION;
      case 25: return SETTL_PARTY_ROLE_CONTRA_INVESTOR_ID;
      case 26: return SETTL_PARTY_ROLE_CONTRA_TRADER;
      case 27: return SETTL_PARTY_ROLE_CORRESPONDENT_BROKER;
      case 28: return SETTL_PARTY_ROLE_CORRESPONDENT_CLEARING_ORGANIZATION;
      case 29: return SETTL_PARTY_ROLE_CUSTODIAN;
      case 30: return SETTL_PARTY_ROLE_CUSTOMER_ACCOUNT;
      case 31: return SETTL_PARTY_ROLE_ENTERING_TRADER;
      case 32: return SETTL_PARTY_ROLE_EXCHANGE;
      case 33: return SETTL_PARTY_ROLE_INTERESTED_PARTY;
      case 34: return SETTL_PARTY_ROLE_INTERMEDIARY;
      case 35: return SETTL_PARTY_ROLE_LIQUIDITY_PROVIDER;
      case 36: return SETTL_PARTY_ROLE_POSITION_ACCOUNT;
      case 37: return SETTL_PARTY_ROLE_REGULATORY_BODY;
      case 38: return SETTL_PARTY_ROLE_SUB_CUSTODIAN;
      case 39: return SETTL_PARTY_ROLE_TRANSFER_TO_FIRM;
      case 40: return SETTL_PARTY_ROLE_INTRODUCING_BROKER;
      case 41: return SETTL_PARTY_ROLE_CONTRA_EXCHANGE;
      case 42: return SETTL_PARTY_ROLE_CONTRA_POSITION_ACCOUNT;
      case 43: return SETTL_PARTY_ROLE_INTERNAL_CARRY_ACCOUNT;
      case 44: return SETTL_PARTY_ROLE_ORDER_ENTRY_OPERATOR_ID;
      case 45: return SETTL_PARTY_ROLE_SECONDARY_ACCOUNT_NUMBER;
      case 46: return SETTL_PARTY_ROLE_ASSET_MANAGER;
      case 47: return SETTL_PARTY_ROLE_CLAIMING_ACCOUNT;
      case 48: return SETTL_PARTY_ROLE_FOREIGN_FIRM;
      case 49: return SETTL_PARTY_ROLE_LARGE_TRADER_REPORTABLE_ACCOUNT;
      case 50: return SETTL_PARTY_ROLE_PLEDGEE_ACCOUNT;
      case 51: return SETTL_PARTY_ROLE_PLEDGOR_ACCOUNT;
      case 52: return SETTL_PARTY_ROLE_SENDER_LOCATION;
      case 53: return SETTL_PARTY_ROLE_SESSION_ID;
      case 54: return SETTL_PARTY_ROLE_THIRD_PARTY_ALLOCATION_FIRM;
      case 55: return SETTL_PARTY_ROLE_TRADER_MNEMONIC;
      case 56: return SETTL_PARTY_ROLE_ACCEPTABLE_COUNTERPARTY;
      case 57: return SETTL_PARTY_ROLE_ENTERING_UNIT;
      case 58: return SETTL_PARTY_ROLE_EXECUTING_UNIT;
      case 59: return SETTL_PARTY_ROLE_UNACCEPTABLE_COUNTERPARTY;
      case 60: return SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_LIQUIDITY;
      case 61: return SETTL_PARTY_ROLE_COMPETENT_AUTHORITY_TRANSACTION_VENUE;
      case 62: return SETTL_PARTY_ROLE_DESK_ID;
      case 63: return SETTL_PARTY_ROLE_EXECUTION_VENUE;
      case 64: return SETTL_PARTY_ROLE_HOME_COMPETENT_AUTHORITY;
      case 65: return SETTL_PARTY_ROLE_HOST_COMPETENT_AUTHORITY;
      case 66: return SETTL_PARTY_ROLE_INVESTMENT_FIRM;
      case 67: return SETTL_PARTY_ROLE_LOCATION_ID;
      case 68: return SETTL_PARTY_ROLE_MARKET_DATA_ENTRY_ORIGINATOR;
      case 69: return SETTL_PARTY_ROLE_MARKET_DATA_MARKET;
      case 70: return SETTL_PARTY_ROLE_MARKET_MAKER;
      case 71: return SETTL_PARTY_ROLE_MULTILATERAL_TRADING_FACILITY;
      case 72: return SETTL_PARTY_ROLE_QUOTE_ORIGINATOR;
      case 73: return SETTL_PARTY_ROLE_REGULATED_MARKET;
      case 74: return SETTL_PARTY_ROLE_REPORTING_INTERMEDIARY;
      case 75: return SETTL_PARTY_ROLE_REPORT_ORIGINATOR;
      case 76: return SETTL_PARTY_ROLE_SYSTEMATIC_INTERNALISER;
      case 77: return SETTL_PARTY_ROLE_ALLOCATION_ENTITY;
      case 78: return SETTL_PARTY_ROLE_BROKER_CLEARING_ID;
      case 79: return SETTL_PARTY_ROLE_PRIME_BROKER;
      case 80: return SETTL_PARTY_ROLE_STEP_OUT_FIRM;
      case 81: return SETTL_PARTY_ROLE_CENTRAL_REGISTRATION_DEPOSITORY;
      case 82: return SETTL_PARTY_ROLE_ACCEPTABLE_SETTLING_COUNTERPARTY;
      case 83: return SETTL_PARTY_ROLE_CLEARING_ACCOUNT;
      case 84: return SETTL_PARTY_ROLE_UNACCEPTABLE_SETTLING_COUNTERPARTY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SettlPartyRoleEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SettlPartyRoleEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SettlPartyRoleEnum>() {
          public SettlPartyRoleEnum findValueByNumber(int number) {
            return SettlPartyRoleEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.getDescriptor().getEnumTypes().get(65);
  }

  private static final SettlPartyRoleEnum[] VALUES = values();

  public static SettlPartyRoleEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SettlPartyRoleEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Common.SettlPartyRoleEnum)
}

