// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf type {@code Common.SettlParties}
 */
public  final class SettlParties extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Common.SettlParties)
    SettlPartiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SettlParties.newBuilder() to construct.
  private SettlParties(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SettlParties() {
    settlPartyId_ = "";
    settlPartyIdSource_ = 0;
    settlPartyRole_ = 0;
    settlPtysSubGrp_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SettlParties();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SettlParties(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            settlPartyId_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            settlPartyIdSource_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            settlPartyRole_ = rawValue;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              settlPtysSubGrp_ = new java.util.ArrayList<org.fixprotocol.components.SettlPtysSubGrp>();
              mutable_bitField0_ |= 0x00000001;
            }
            settlPtysSubGrp_.add(
                input.readMessage(org.fixprotocol.components.SettlPtysSubGrp.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        settlPtysSubGrp_ = java.util.Collections.unmodifiableList(settlPtysSubGrp_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.internal_static_Common_SettlParties_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.fixprotocol.components.Common.internal_static_Common_SettlParties_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.fixprotocol.components.SettlParties.class, org.fixprotocol.components.SettlParties.Builder.class);
  }

  public static final int SETTL_PARTY_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object settlPartyId_;
  /**
   * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.lang.String getSettlPartyId() {
    java.lang.Object ref = settlPartyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      settlPartyId_ = s;
      return s;
    }
  }
  /**
   * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public com.google.protobuf.ByteString
      getSettlPartyIdBytes() {
    java.lang.Object ref = settlPartyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      settlPartyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SETTL_PARTY_ID_SOURCE_FIELD_NUMBER = 2;
  private int settlPartyIdSource_;
  /**
   * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public int getSettlPartyIdSourceValue() {
    return settlPartyIdSource_;
  }
  /**
   * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.SettlPartyIDSourceEnum getSettlPartyIdSource() {
    @SuppressWarnings("deprecation")
    org.fixprotocol.components.SettlPartyIDSourceEnum result = org.fixprotocol.components.SettlPartyIDSourceEnum.valueOf(settlPartyIdSource_);
    return result == null ? org.fixprotocol.components.SettlPartyIDSourceEnum.UNRECOGNIZED : result;
  }

  public static final int SETTL_PARTY_ROLE_FIELD_NUMBER = 3;
  private int settlPartyRole_;
  /**
   * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public int getSettlPartyRoleValue() {
    return settlPartyRole_;
  }
  /**
   * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.SettlPartyRoleEnum getSettlPartyRole() {
    @SuppressWarnings("deprecation")
    org.fixprotocol.components.SettlPartyRoleEnum result = org.fixprotocol.components.SettlPartyRoleEnum.valueOf(settlPartyRole_);
    return result == null ? org.fixprotocol.components.SettlPartyRoleEnum.UNRECOGNIZED : result;
  }

  public static final int SETTL_PTYS_SUB_GRP_FIELD_NUMBER = 4;
  private java.util.List<org.fixprotocol.components.SettlPtysSubGrp> settlPtysSubGrp_;
  /**
   * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.util.List<org.fixprotocol.components.SettlPtysSubGrp> getSettlPtysSubGrpList() {
    return settlPtysSubGrp_;
  }
  /**
   * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public java.util.List<? extends org.fixprotocol.components.SettlPtysSubGrpOrBuilder> 
      getSettlPtysSubGrpOrBuilderList() {
    return settlPtysSubGrp_;
  }
  /**
   * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public int getSettlPtysSubGrpCount() {
    return settlPtysSubGrp_.size();
  }
  /**
   * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.SettlPtysSubGrp getSettlPtysSubGrp(int index) {
    return settlPtysSubGrp_.get(index);
  }
  /**
   * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  public org.fixprotocol.components.SettlPtysSubGrpOrBuilder getSettlPtysSubGrpOrBuilder(
      int index) {
    return settlPtysSubGrp_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSettlPartyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, settlPartyId_);
    }
    if (settlPartyIdSource_ != org.fixprotocol.components.SettlPartyIDSourceEnum.SETTL_PARTY_ID_SOURCE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, settlPartyIdSource_);
    }
    if (settlPartyRole_ != org.fixprotocol.components.SettlPartyRoleEnum.SETTL_PARTY_ROLE_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, settlPartyRole_);
    }
    for (int i = 0; i < settlPtysSubGrp_.size(); i++) {
      output.writeMessage(4, settlPtysSubGrp_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSettlPartyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, settlPartyId_);
    }
    if (settlPartyIdSource_ != org.fixprotocol.components.SettlPartyIDSourceEnum.SETTL_PARTY_ID_SOURCE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, settlPartyIdSource_);
    }
    if (settlPartyRole_ != org.fixprotocol.components.SettlPartyRoleEnum.SETTL_PARTY_ROLE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, settlPartyRole_);
    }
    for (int i = 0; i < settlPtysSubGrp_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, settlPtysSubGrp_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.fixprotocol.components.SettlParties)) {
      return super.equals(obj);
    }
    org.fixprotocol.components.SettlParties other = (org.fixprotocol.components.SettlParties) obj;

    if (!getSettlPartyId()
        .equals(other.getSettlPartyId())) return false;
    if (settlPartyIdSource_ != other.settlPartyIdSource_) return false;
    if (settlPartyRole_ != other.settlPartyRole_) return false;
    if (!getSettlPtysSubGrpList()
        .equals(other.getSettlPtysSubGrpList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETTL_PARTY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSettlPartyId().hashCode();
    hash = (37 * hash) + SETTL_PARTY_ID_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + settlPartyIdSource_;
    hash = (37 * hash) + SETTL_PARTY_ROLE_FIELD_NUMBER;
    hash = (53 * hash) + settlPartyRole_;
    if (getSettlPtysSubGrpCount() > 0) {
      hash = (37 * hash) + SETTL_PTYS_SUB_GRP_FIELD_NUMBER;
      hash = (53 * hash) + getSettlPtysSubGrpList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.fixprotocol.components.SettlParties parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.SettlParties parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.SettlParties parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.SettlParties parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.fixprotocol.components.SettlParties prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Common.SettlParties}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Common.SettlParties)
      org.fixprotocol.components.SettlPartiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fixprotocol.components.Common.internal_static_Common_SettlParties_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fixprotocol.components.Common.internal_static_Common_SettlParties_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fixprotocol.components.SettlParties.class, org.fixprotocol.components.SettlParties.Builder.class);
    }

    // Construct using org.fixprotocol.components.SettlParties.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSettlPtysSubGrpFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      settlPartyId_ = "";

      settlPartyIdSource_ = 0;

      settlPartyRole_ = 0;

      if (settlPtysSubGrpBuilder_ == null) {
        settlPtysSubGrp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        settlPtysSubGrpBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.fixprotocol.components.Common.internal_static_Common_SettlParties_descriptor;
    }

    @java.lang.Override
    public org.fixprotocol.components.SettlParties getDefaultInstanceForType() {
      return org.fixprotocol.components.SettlParties.getDefaultInstance();
    }

    @java.lang.Override
    public org.fixprotocol.components.SettlParties build() {
      org.fixprotocol.components.SettlParties result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.fixprotocol.components.SettlParties buildPartial() {
      org.fixprotocol.components.SettlParties result = new org.fixprotocol.components.SettlParties(this);
      int from_bitField0_ = bitField0_;
      result.settlPartyId_ = settlPartyId_;
      result.settlPartyIdSource_ = settlPartyIdSource_;
      result.settlPartyRole_ = settlPartyRole_;
      if (settlPtysSubGrpBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          settlPtysSubGrp_ = java.util.Collections.unmodifiableList(settlPtysSubGrp_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.settlPtysSubGrp_ = settlPtysSubGrp_;
      } else {
        result.settlPtysSubGrp_ = settlPtysSubGrpBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.fixprotocol.components.SettlParties) {
        return mergeFrom((org.fixprotocol.components.SettlParties)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.fixprotocol.components.SettlParties other) {
      if (other == org.fixprotocol.components.SettlParties.getDefaultInstance()) return this;
      if (!other.getSettlPartyId().isEmpty()) {
        settlPartyId_ = other.settlPartyId_;
        onChanged();
      }
      if (other.settlPartyIdSource_ != 0) {
        setSettlPartyIdSourceValue(other.getSettlPartyIdSourceValue());
      }
      if (other.settlPartyRole_ != 0) {
        setSettlPartyRoleValue(other.getSettlPartyRoleValue());
      }
      if (settlPtysSubGrpBuilder_ == null) {
        if (!other.settlPtysSubGrp_.isEmpty()) {
          if (settlPtysSubGrp_.isEmpty()) {
            settlPtysSubGrp_ = other.settlPtysSubGrp_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSettlPtysSubGrpIsMutable();
            settlPtysSubGrp_.addAll(other.settlPtysSubGrp_);
          }
          onChanged();
        }
      } else {
        if (!other.settlPtysSubGrp_.isEmpty()) {
          if (settlPtysSubGrpBuilder_.isEmpty()) {
            settlPtysSubGrpBuilder_.dispose();
            settlPtysSubGrpBuilder_ = null;
            settlPtysSubGrp_ = other.settlPtysSubGrp_;
            bitField0_ = (bitField0_ & ~0x00000001);
            settlPtysSubGrpBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSettlPtysSubGrpFieldBuilder() : null;
          } else {
            settlPtysSubGrpBuilder_.addAllMessages(other.settlPtysSubGrp_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.fixprotocol.components.SettlParties parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.fixprotocol.components.SettlParties) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object settlPartyId_ = "";
    /**
     * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.lang.String getSettlPartyId() {
      java.lang.Object ref = settlPartyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        settlPartyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public com.google.protobuf.ByteString
        getSettlPartyIdBytes() {
      java.lang.Object ref = settlPartyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        settlPartyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPartyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      settlPartyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearSettlPartyId() {
      
      settlPartyId_ = getDefaultInstance().getSettlPartyId();
      onChanged();
      return this;
    }
    /**
     * <code>string settl_party_id = 1 [(.fix.tag) = 782, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPartyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      settlPartyId_ = value;
      onChanged();
      return this;
    }

    private int settlPartyIdSource_ = 0;
    /**
     * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public int getSettlPartyIdSourceValue() {
      return settlPartyIdSource_;
    }
    /**
     * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPartyIdSourceValue(int value) {
      settlPartyIdSource_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPartyIDSourceEnum getSettlPartyIdSource() {
      @SuppressWarnings("deprecation")
      org.fixprotocol.components.SettlPartyIDSourceEnum result = org.fixprotocol.components.SettlPartyIDSourceEnum.valueOf(settlPartyIdSource_);
      return result == null ? org.fixprotocol.components.SettlPartyIDSourceEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPartyIdSource(org.fixprotocol.components.SettlPartyIDSourceEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      settlPartyIdSource_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Common.SettlPartyIDSourceEnum settl_party_id_source = 2 [(.fix.tag) = 783, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearSettlPartyIdSource() {
      
      settlPartyIdSource_ = 0;
      onChanged();
      return this;
    }

    private int settlPartyRole_ = 0;
    /**
     * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public int getSettlPartyRoleValue() {
      return settlPartyRole_;
    }
    /**
     * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPartyRoleValue(int value) {
      settlPartyRole_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPartyRoleEnum getSettlPartyRole() {
      @SuppressWarnings("deprecation")
      org.fixprotocol.components.SettlPartyRoleEnum result = org.fixprotocol.components.SettlPartyRoleEnum.valueOf(settlPartyRole_);
      return result == null ? org.fixprotocol.components.SettlPartyRoleEnum.UNRECOGNIZED : result;
    }
    /**
     * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPartyRole(org.fixprotocol.components.SettlPartyRoleEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      settlPartyRole_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.Common.SettlPartyRoleEnum settl_party_role = 3 [(.fix.tag) = 784, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearSettlPartyRole() {
      
      settlPartyRole_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.fixprotocol.components.SettlPtysSubGrp> settlPtysSubGrp_ =
      java.util.Collections.emptyList();
    private void ensureSettlPtysSubGrpIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        settlPtysSubGrp_ = new java.util.ArrayList<org.fixprotocol.components.SettlPtysSubGrp>(settlPtysSubGrp_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.fixprotocol.components.SettlPtysSubGrp, org.fixprotocol.components.SettlPtysSubGrp.Builder, org.fixprotocol.components.SettlPtysSubGrpOrBuilder> settlPtysSubGrpBuilder_;

    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.util.List<org.fixprotocol.components.SettlPtysSubGrp> getSettlPtysSubGrpList() {
      if (settlPtysSubGrpBuilder_ == null) {
        return java.util.Collections.unmodifiableList(settlPtysSubGrp_);
      } else {
        return settlPtysSubGrpBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public int getSettlPtysSubGrpCount() {
      if (settlPtysSubGrpBuilder_ == null) {
        return settlPtysSubGrp_.size();
      } else {
        return settlPtysSubGrpBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPtysSubGrp getSettlPtysSubGrp(int index) {
      if (settlPtysSubGrpBuilder_ == null) {
        return settlPtysSubGrp_.get(index);
      } else {
        return settlPtysSubGrpBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPtysSubGrp(
        int index, org.fixprotocol.components.SettlPtysSubGrp value) {
      if (settlPtysSubGrpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.set(index, value);
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder setSettlPtysSubGrp(
        int index, org.fixprotocol.components.SettlPtysSubGrp.Builder builderForValue) {
      if (settlPtysSubGrpBuilder_ == null) {
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.set(index, builderForValue.build());
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addSettlPtysSubGrp(org.fixprotocol.components.SettlPtysSubGrp value) {
      if (settlPtysSubGrpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.add(value);
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addSettlPtysSubGrp(
        int index, org.fixprotocol.components.SettlPtysSubGrp value) {
      if (settlPtysSubGrpBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.add(index, value);
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addSettlPtysSubGrp(
        org.fixprotocol.components.SettlPtysSubGrp.Builder builderForValue) {
      if (settlPtysSubGrpBuilder_ == null) {
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.add(builderForValue.build());
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addSettlPtysSubGrp(
        int index, org.fixprotocol.components.SettlPtysSubGrp.Builder builderForValue) {
      if (settlPtysSubGrpBuilder_ == null) {
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.add(index, builderForValue.build());
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder addAllSettlPtysSubGrp(
        java.lang.Iterable<? extends org.fixprotocol.components.SettlPtysSubGrp> values) {
      if (settlPtysSubGrpBuilder_ == null) {
        ensureSettlPtysSubGrpIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, settlPtysSubGrp_);
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder clearSettlPtysSubGrp() {
      if (settlPtysSubGrpBuilder_ == null) {
        settlPtysSubGrp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public Builder removeSettlPtysSubGrp(int index) {
      if (settlPtysSubGrpBuilder_ == null) {
        ensureSettlPtysSubGrpIsMutable();
        settlPtysSubGrp_.remove(index);
        onChanged();
      } else {
        settlPtysSubGrpBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPtysSubGrp.Builder getSettlPtysSubGrpBuilder(
        int index) {
      return getSettlPtysSubGrpFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPtysSubGrpOrBuilder getSettlPtysSubGrpOrBuilder(
        int index) {
      if (settlPtysSubGrpBuilder_ == null) {
        return settlPtysSubGrp_.get(index);  } else {
        return settlPtysSubGrpBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.util.List<? extends org.fixprotocol.components.SettlPtysSubGrpOrBuilder> 
         getSettlPtysSubGrpOrBuilderList() {
      if (settlPtysSubGrpBuilder_ != null) {
        return settlPtysSubGrpBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(settlPtysSubGrp_);
      }
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPtysSubGrp.Builder addSettlPtysSubGrpBuilder() {
      return getSettlPtysSubGrpFieldBuilder().addBuilder(
          org.fixprotocol.components.SettlPtysSubGrp.getDefaultInstance());
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public org.fixprotocol.components.SettlPtysSubGrp.Builder addSettlPtysSubGrpBuilder(
        int index) {
      return getSettlPtysSubGrpFieldBuilder().addBuilder(
          index, org.fixprotocol.components.SettlPtysSubGrp.getDefaultInstance());
    }
    /**
     * <code>repeated .Common.SettlPtysSubGrp settl_ptys_sub_grp = 4 [(.fix.field_added) = VERSION_FIX_4_4];</code>
     */
    public java.util.List<org.fixprotocol.components.SettlPtysSubGrp.Builder> 
         getSettlPtysSubGrpBuilderList() {
      return getSettlPtysSubGrpFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.fixprotocol.components.SettlPtysSubGrp, org.fixprotocol.components.SettlPtysSubGrp.Builder, org.fixprotocol.components.SettlPtysSubGrpOrBuilder> 
        getSettlPtysSubGrpFieldBuilder() {
      if (settlPtysSubGrpBuilder_ == null) {
        settlPtysSubGrpBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.fixprotocol.components.SettlPtysSubGrp, org.fixprotocol.components.SettlPtysSubGrp.Builder, org.fixprotocol.components.SettlPtysSubGrpOrBuilder>(
                settlPtysSubGrp_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        settlPtysSubGrp_ = null;
      }
      return settlPtysSubGrpBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Common.SettlParties)
  }

  // @@protoc_insertion_point(class_scope:Common.SettlParties)
  private static final org.fixprotocol.components.SettlParties DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.fixprotocol.components.SettlParties();
  }

  public static org.fixprotocol.components.SettlParties getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SettlParties>
      PARSER = new com.google.protobuf.AbstractParser<SettlParties>() {
    @java.lang.Override
    public SettlParties parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SettlParties(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SettlParties> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SettlParties> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.fixprotocol.components.SettlParties getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

