// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

public interface TradingSessionRulesGrpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Common.TradingSessionRulesGrp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Common.TradingSessionIDEnum trading_session_id = 1 [(.fix.tag) = 336, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The enum numeric value on the wire for tradingSessionId.
   */
  int getTradingSessionIdValue();
  /**
   * <code>.Common.TradingSessionIDEnum trading_session_id = 1 [(.fix.tag) = 336, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The tradingSessionId.
   */
  org.fixprotocol.components.TradingSessionIDEnum getTradingSessionId();

  /**
   * <code>fixed32 trading_session_id_reserved100plus = 2 [(.fix.tag) = 336, (.fix.type) = DATATYPE_RESERVED100PLUS, (.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The tradingSessionIdReserved100plus.
   */
  int getTradingSessionIdReserved100Plus();

  /**
   * <code>.Common.TradingSessionRules trading_session_rules = 3 [(.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return Whether the tradingSessionRules field is set.
   */
  boolean hasTradingSessionRules();
  /**
   * <code>.Common.TradingSessionRules trading_session_rules = 3 [(.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The tradingSessionRules.
   */
  org.fixprotocol.components.TradingSessionRules getTradingSessionRules();
  /**
   * <code>.Common.TradingSessionRules trading_session_rules = 3 [(.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.TradingSessionRulesOrBuilder getTradingSessionRulesOrBuilder();

  /**
   * <code>.Common.TradingSessionSubIDEnum trading_session_sub_id = 4 [(.fix.tag) = 625, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The enum numeric value on the wire for tradingSessionSubId.
   */
  int getTradingSessionSubIdValue();
  /**
   * <code>.Common.TradingSessionSubIDEnum trading_session_sub_id = 4 [(.fix.tag) = 625, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The tradingSessionSubId.
   */
  org.fixprotocol.components.TradingSessionSubIDEnum getTradingSessionSubId();

  /**
   * <code>fixed32 trading_session_sub_id_reserved100plus = 5 [(.fix.tag) = 625, (.fix.type) = DATATYPE_RESERVED100PLUS, (.fix.field_added) = VERSION_FIX_5_0];</code>
   * @return The tradingSessionSubIdReserved100plus.
   */
  int getTradingSessionSubIdReserved100Plus();

  public org.fixprotocol.components.TradingSessionRulesGrp.TradingSessionIdUnionCase getTradingSessionIdUnionCase();

  public org.fixprotocol.components.TradingSessionRulesGrp.TradingSessionSubIdUnionCase getTradingSessionSubIdUnionCase();
}
