// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

public interface UnderlyingInstrumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Common.UnderlyingInstrument)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string encoded_underlying_issuer = 1 [(.fix.tag) = 363, (.fix.type) = DATATYPE_DATA, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getEncodedUnderlyingIssuer();
  /**
   * <code>string encoded_underlying_issuer = 1 [(.fix.tag) = 363, (.fix.type) = DATATYPE_DATA, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getEncodedUnderlyingIssuerBytes();

  /**
   * <code>sfixed64 encoded_underlying_issuer_len = 2 [(.fix.tag) = 362, (.fix.type) = DATATYPE_LENGTH, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  long getEncodedUnderlyingIssuerLen();

  /**
   * <code>string encoded_underlying_security_desc = 3 [(.fix.tag) = 365, (.fix.type) = DATATYPE_DATA, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getEncodedUnderlyingSecurityDesc();
  /**
   * <code>string encoded_underlying_security_desc = 3 [(.fix.tag) = 365, (.fix.type) = DATATYPE_DATA, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getEncodedUnderlyingSecurityDescBytes();

  /**
   * <code>sfixed64 encoded_underlying_security_desc_len = 4 [(.fix.tag) = 364, (.fix.type) = DATATYPE_LENGTH, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  long getEncodedUnderlyingSecurityDescLen();

  /**
   * <code>string underlying_cfi_code = 5 [(.fix.tag) = 463, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingCfiCode();
  /**
   * <code>string underlying_cfi_code = 5 [(.fix.tag) = 463, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingCfiCodeBytes();

  /**
   * <code>.fix.Decimal64 underlying_contract_multiplier = 6 [(.fix.tag) = 436, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  boolean hasUnderlyingContractMultiplier();
  /**
   * <code>.fix.Decimal64 underlying_contract_multiplier = 6 [(.fix.tag) = 436, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingContractMultiplier();
  /**
   * <code>.fix.Decimal64 underlying_contract_multiplier = 6 [(.fix.tag) = 436, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingContractMultiplierOrBuilder();

  /**
   * <code>string underlying_country_of_issue = 7 [(.fix.tag) = 592, (.fix.type) = DATATYPE_COUNTRY, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingCountryOfIssue();
  /**
   * <code>string underlying_country_of_issue = 7 [(.fix.tag) = 592, (.fix.type) = DATATYPE_COUNTRY, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingCountryOfIssueBytes();

  /**
   * <code>sfixed32 underlying_coupon_payment_date = 8 [(.fix.tag) = 241, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingCouponPaymentDate();

  /**
   * <code>.fix.Decimal64 underlying_coupon_rate = 9 [(.fix.tag) = 435, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  boolean hasUnderlyingCouponRate();
  /**
   * <code>.fix.Decimal64 underlying_coupon_rate = 9 [(.fix.tag) = 435, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingCouponRate();
  /**
   * <code>.fix.Decimal64 underlying_coupon_rate = 9 [(.fix.tag) = 435, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingCouponRateOrBuilder();

  /**
   * <code>string underlying_credit_rating = 10 [(.fix.tag) = 256, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingCreditRating();
  /**
   * <code>string underlying_credit_rating = 10 [(.fix.tag) = 256, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingCreditRatingBytes();

  /**
   * <code>.fix.Decimal64 underlying_factor = 11 [(.fix.tag) = 246, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  boolean hasUnderlyingFactor();
  /**
   * <code>.fix.Decimal64 underlying_factor = 11 [(.fix.tag) = 246, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingFactor();
  /**
   * <code>.fix.Decimal64 underlying_factor = 11 [(.fix.tag) = 246, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingFactorOrBuilder();

  /**
   * <code>string underlying_instr_registry = 12 [(.fix.tag) = 595, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingInstrRegistry();
  /**
   * <code>string underlying_instr_registry = 12 [(.fix.tag) = 595, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingInstrRegistryBytes();

  /**
   * <code>sfixed32 underlying_issue_date = 13 [(.fix.tag) = 242, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingIssueDate();

  /**
   * <code>string underlying_issuer = 14 [(.fix.tag) = 306, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingIssuer();
  /**
   * <code>string underlying_issuer = 14 [(.fix.tag) = 306, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingIssuerBytes();

  /**
   * <code>string underlying_locale_of_issue = 15 [(.fix.tag) = 594, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingLocaleOfIssue();
  /**
   * <code>string underlying_locale_of_issue = 15 [(.fix.tag) = 594, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingLocaleOfIssueBytes();

  /**
   * <code>sfixed32 underlying_maturity_date = 16 [(.fix.tag) = 542, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingMaturityDate();

  /**
   * <code>sfixed32 underlying_maturity_month_year = 17 [(.fix.tag) = 313, (.fix.type) = DATATYPE_MONTH_YEAR, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingMaturityMonthYear();

  /**
   * <code>bytes underlying_opt_attribute = 18 [(.fix.tag) = 317, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString getUnderlyingOptAttribute();

  /**
   * <code>.Common.UnderlyingProductEnum underlying_product = 19 [(.fix.tag) = 462, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingProductValue();
  /**
   * <code>.Common.UnderlyingProductEnum underlying_product = 19 [(.fix.tag) = 462, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.UnderlyingProductEnum getUnderlyingProduct();

  /**
   * <code>sfixed64 underlying_put_or_call = 20 [(.fix.tag) = 315, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  long getUnderlyingPutOrCall();

  /**
   * <code>sfixed32 underlying_redemption_date = 21 [(.fix.tag) = 247, (.fix.type) = DATATYPE_LOCAL_MKT_DATE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingRedemptionDate();

  /**
   * <code>string underlying_repo_collateral_security_type = 22 [(.fix.tag) = 243, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingRepoCollateralSecurityType();
  /**
   * <code>string underlying_repo_collateral_security_type = 22 [(.fix.tag) = 243, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingRepoCollateralSecurityTypeBytes();

  /**
   * <code>.fix.Decimal64 underlying_repurchase_rate = 23 [(.fix.tag) = 245, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  boolean hasUnderlyingRepurchaseRate();
  /**
   * <code>.fix.Decimal64 underlying_repurchase_rate = 23 [(.fix.tag) = 245, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingRepurchaseRate();
  /**
   * <code>.fix.Decimal64 underlying_repurchase_rate = 23 [(.fix.tag) = 245, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingRepurchaseRateOrBuilder();

  /**
   * <code>sfixed64 underlying_repurchase_term = 24 [(.fix.tag) = 244, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  long getUnderlyingRepurchaseTerm();

  /**
   * <code>string underlying_security_desc = 25 [(.fix.tag) = 307, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingSecurityDesc();
  /**
   * <code>string underlying_security_desc = 25 [(.fix.tag) = 307, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingSecurityDescBytes();

  /**
   * <code>string underlying_security_exchange = 26 [(.fix.tag) = 308, (.fix.type) = DATATYPE_EXCHANGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingSecurityExchange();
  /**
   * <code>string underlying_security_exchange = 26 [(.fix.tag) = 308, (.fix.type) = DATATYPE_EXCHANGE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingSecurityExchangeBytes();

  /**
   * <code>string underlying_security_id = 27 [(.fix.tag) = 309, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingSecurityId();
  /**
   * <code>string underlying_security_id = 27 [(.fix.tag) = 309, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingSecurityIdBytes();

  /**
   * <code>.Common.UnderlyingSecurityIDSourceEnum underlying_security_id_source = 28 [(.fix.tag) = 305, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingSecurityIdSourceValue();
  /**
   * <code>.Common.UnderlyingSecurityIDSourceEnum underlying_security_id_source = 28 [(.fix.tag) = 305, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.UnderlyingSecurityIDSourceEnum getUnderlyingSecurityIdSource();

  /**
   * <code>.Common.UnderlyingSecurityTypeEnum underlying_security_type = 29 [(.fix.tag) = 310, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingSecurityTypeValue();
  /**
   * <code>.Common.UnderlyingSecurityTypeEnum underlying_security_type = 29 [(.fix.tag) = 310, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.UnderlyingSecurityTypeEnum getUnderlyingSecurityType();

  /**
   * <code>string underlying_state_or_province_of_issue = 30 [(.fix.tag) = 593, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingStateOrProvinceOfIssue();
  /**
   * <code>string underlying_state_or_province_of_issue = 30 [(.fix.tag) = 593, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingStateOrProvinceOfIssueBytes();

  /**
   * <code>.fix.Decimal64 underlying_strike_price = 31 [(.fix.tag) = 316, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  boolean hasUnderlyingStrikePrice();
  /**
   * <code>.fix.Decimal64 underlying_strike_price = 31 [(.fix.tag) = 316, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingStrikePrice();
  /**
   * <code>.fix.Decimal64 underlying_strike_price = 31 [(.fix.tag) = 316, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingStrikePriceOrBuilder();

  /**
   * <code>string underlying_symbol = 32 [(.fix.tag) = 311, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  java.lang.String getUnderlyingSymbol();
  /**
   * <code>string underlying_symbol = 32 [(.fix.tag) = 311, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingSymbolBytes();

  /**
   * <code>.Common.UnderlyingSymbolSfxEnum underlying_symbol_sfx = 33 [(.fix.tag) = 312, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  int getUnderlyingSymbolSfxValue();
  /**
   * <code>.Common.UnderlyingSymbolSfxEnum underlying_symbol_sfx = 33 [(.fix.tag) = 312, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_3];</code>
   */
  org.fixprotocol.components.UnderlyingSymbolSfxEnum getUnderlyingSymbolSfx();

  /**
   * <code>repeated .Common.UndSecAltIDGrp und_sec_alt_id_grp = 34 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.util.List<org.fixprotocol.components.UndSecAltIDGrp> 
      getUndSecAltIdGrpList();
  /**
   * <code>repeated .Common.UndSecAltIDGrp und_sec_alt_id_grp = 34 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UndSecAltIDGrp getUndSecAltIdGrp(int index);
  /**
   * <code>repeated .Common.UndSecAltIDGrp und_sec_alt_id_grp = 34 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUndSecAltIdGrpCount();
  /**
   * <code>repeated .Common.UndSecAltIDGrp und_sec_alt_id_grp = 34 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.util.List<? extends org.fixprotocol.components.UndSecAltIDGrpOrBuilder> 
      getUndSecAltIdGrpOrBuilderList();
  /**
   * <code>repeated .Common.UndSecAltIDGrp und_sec_alt_id_grp = 34 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UndSecAltIDGrpOrBuilder getUndSecAltIdGrpOrBuilder(
      int index);

  /**
   * <code>.fix.Decimal64 underlying_adjusted_quantity = 35 [(.fix.tag) = 1044, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingAdjustedQuantity();
  /**
   * <code>.fix.Decimal64 underlying_adjusted_quantity = 35 [(.fix.tag) = 1044, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingAdjustedQuantity();
  /**
   * <code>.fix.Decimal64 underlying_adjusted_quantity = 35 [(.fix.tag) = 1044, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingAdjustedQuantityOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_allocation_percent = 36 [(.fix.tag) = 972, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingAllocationPercent();
  /**
   * <code>.fix.Decimal64 underlying_allocation_percent = 36 [(.fix.tag) = 972, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingAllocationPercent();
  /**
   * <code>.fix.Decimal64 underlying_allocation_percent = 36 [(.fix.tag) = 972, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingAllocationPercentOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_cap_value = 37 [(.fix.tag) = 1038, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingCapValue();
  /**
   * <code>.fix.Decimal64 underlying_cap_value = 37 [(.fix.tag) = 1038, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingCapValue();
  /**
   * <code>.fix.Decimal64 underlying_cap_value = 37 [(.fix.tag) = 1038, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingCapValueOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_cash_amount = 38 [(.fix.tag) = 973, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingCashAmount();
  /**
   * <code>.fix.Decimal64 underlying_cash_amount = 38 [(.fix.tag) = 973, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingCashAmount();
  /**
   * <code>.fix.Decimal64 underlying_cash_amount = 38 [(.fix.tag) = 973, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingCashAmountOrBuilder();

  /**
   * <code>.Common.UnderlyingCashTypeEnum underlying_cash_type = 39 [(.fix.tag) = 974, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUnderlyingCashTypeValue();
  /**
   * <code>.Common.UnderlyingCashTypeEnum underlying_cash_type = 39 [(.fix.tag) = 974, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingCashTypeEnum getUnderlyingCashType();

  /**
   * <code>string underlying_cp_program = 40 [(.fix.tag) = 877, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getUnderlyingCpProgram();
  /**
   * <code>string underlying_cp_program = 40 [(.fix.tag) = 877, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingCpProgramBytes();

  /**
   * <code>string underlying_cp_reg_type = 41 [(.fix.tag) = 878, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getUnderlyingCpRegType();
  /**
   * <code>string underlying_cp_reg_type = 41 [(.fix.tag) = 878, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingCpRegTypeBytes();

  /**
   * <code>string underlying_currency = 42 [(.fix.tag) = 318, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getUnderlyingCurrency();
  /**
   * <code>string underlying_currency = 42 [(.fix.tag) = 318, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingCurrencyBytes();

  /**
   * <code>.fix.Decimal64 underlying_current_value = 43 [(.fix.tag) = 885, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingCurrentValue();
  /**
   * <code>.fix.Decimal64 underlying_current_value = 43 [(.fix.tag) = 885, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingCurrentValue();
  /**
   * <code>.fix.Decimal64 underlying_current_value = 43 [(.fix.tag) = 885, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingCurrentValueOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_dirty_price = 44 [(.fix.tag) = 882, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingDirtyPrice();
  /**
   * <code>.fix.Decimal64 underlying_dirty_price = 44 [(.fix.tag) = 882, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingDirtyPrice();
  /**
   * <code>.fix.Decimal64 underlying_dirty_price = 44 [(.fix.tag) = 882, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingDirtyPriceOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_end_price = 45 [(.fix.tag) = 883, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingEndPrice();
  /**
   * <code>.fix.Decimal64 underlying_end_price = 45 [(.fix.tag) = 883, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingEndPrice();
  /**
   * <code>.fix.Decimal64 underlying_end_price = 45 [(.fix.tag) = 883, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingEndPriceOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_end_value = 46 [(.fix.tag) = 886, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingEndValue();
  /**
   * <code>.fix.Decimal64 underlying_end_value = 46 [(.fix.tag) = 886, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingEndValue();
  /**
   * <code>.fix.Decimal64 underlying_end_value = 46 [(.fix.tag) = 886, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingEndValueOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_fx_rate = 47 [(.fix.tag) = 1045, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingFxRate();
  /**
   * <code>.fix.Decimal64 underlying_fx_rate = 47 [(.fix.tag) = 1045, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingFxRate();
  /**
   * <code>.fix.Decimal64 underlying_fx_rate = 47 [(.fix.tag) = 1045, (.fix.type) = DATATYPE_FLOAT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingFxRateOrBuilder();

  /**
   * <code>.Common.UnderlyingFXRateCalcEnum underlying_fx_rate_calc = 48 [(.fix.tag) = 1046, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUnderlyingFxRateCalcValue();
  /**
   * <code>.Common.UnderlyingFXRateCalcEnum underlying_fx_rate_calc = 48 [(.fix.tag) = 1046, (.fix.type) = DATATYPE_CHAR, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingFXRateCalcEnum getUnderlyingFxRateCalc();

  /**
   * <code>.fix.Decimal64 underlying_px = 49 [(.fix.tag) = 810, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingPx();
  /**
   * <code>.fix.Decimal64 underlying_px = 49 [(.fix.tag) = 810, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingPx();
  /**
   * <code>.fix.Decimal64 underlying_px = 49 [(.fix.tag) = 810, (.fix.type) = DATATYPE_PRICE, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingPxOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_qty = 50 [(.fix.tag) = 879, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingQty();
  /**
   * <code>.fix.Decimal64 underlying_qty = 50 [(.fix.tag) = 879, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingQty();
  /**
   * <code>.fix.Decimal64 underlying_qty = 50 [(.fix.tag) = 879, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingQtyOrBuilder();

  /**
   * <code>string underlying_security_sub_type = 51 [(.fix.tag) = 763, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getUnderlyingSecuritySubType();
  /**
   * <code>string underlying_security_sub_type = 51 [(.fix.tag) = 763, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingSecuritySubTypeBytes();

  /**
   * <code>string underlying_settl_method = 52 [(.fix.tag) = 1039, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getUnderlyingSettlMethod();
  /**
   * <code>string underlying_settl_method = 52 [(.fix.tag) = 1039, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingSettlMethodBytes();

  /**
   * <code>.Common.UnderlyingSettlementTypeEnum underlying_settlement_type = 53 [(.fix.tag) = 975, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUnderlyingSettlementTypeValue();
  /**
   * <code>.Common.UnderlyingSettlementTypeEnum underlying_settlement_type = 53 [(.fix.tag) = 975, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingSettlementTypeEnum getUnderlyingSettlementType();

  /**
   * <code>.fix.Decimal64 underlying_start_value = 54 [(.fix.tag) = 884, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  boolean hasUnderlyingStartValue();
  /**
   * <code>.fix.Decimal64 underlying_start_value = 54 [(.fix.tag) = 884, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingStartValue();
  /**
   * <code>.fix.Decimal64 underlying_start_value = 54 [(.fix.tag) = 884, (.fix.type) = DATATYPE_AMT, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingStartValueOrBuilder();

  /**
   * <code>repeated .Common.UnderlyingStipulations underlying_stipulations = 55 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.util.List<org.fixprotocol.components.UnderlyingStipulations> 
      getUnderlyingStipulationsList();
  /**
   * <code>repeated .Common.UnderlyingStipulations underlying_stipulations = 55 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingStipulations getUnderlyingStipulations(int index);
  /**
   * <code>repeated .Common.UnderlyingStipulations underlying_stipulations = 55 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUnderlyingStipulationsCount();
  /**
   * <code>repeated .Common.UnderlyingStipulations underlying_stipulations = 55 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.util.List<? extends org.fixprotocol.components.UnderlyingStipulationsOrBuilder> 
      getUnderlyingStipulationsOrBuilderList();
  /**
   * <code>repeated .Common.UnderlyingStipulations underlying_stipulations = 55 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingStipulationsOrBuilder getUnderlyingStipulationsOrBuilder(
      int index);

  /**
   * <code>string underlying_strike_currency = 56 [(.fix.tag) = 941, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.lang.String getUnderlyingStrikeCurrency();
  /**
   * <code>string underlying_strike_currency = 56 [(.fix.tag) = 941, (.fix.type) = DATATYPE_CURRENCY, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  com.google.protobuf.ByteString
      getUnderlyingStrikeCurrencyBytes();

  /**
   * <code>.Common.UnderlyingTimeUnitEnum underlying_time_unit = 57 [(.fix.tag) = 1000, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUnderlyingTimeUnitValue();
  /**
   * <code>.Common.UnderlyingTimeUnitEnum underlying_time_unit = 57 [(.fix.tag) = 1000, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingTimeUnitEnum getUnderlyingTimeUnit();

  /**
   * <code>.Common.UnderlyingUnitOfMeasureEnum underlying_unit_of_measure = 58 [(.fix.tag) = 998, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUnderlyingUnitOfMeasureValue();
  /**
   * <code>.Common.UnderlyingUnitOfMeasureEnum underlying_unit_of_measure = 58 [(.fix.tag) = 998, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UnderlyingUnitOfMeasureEnum getUnderlyingUnitOfMeasure();

  /**
   * <code>repeated .Common.UndlyInstrumentParties undly_instrument_parties = 59 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.util.List<org.fixprotocol.components.UndlyInstrumentParties> 
      getUndlyInstrumentPartiesList();
  /**
   * <code>repeated .Common.UndlyInstrumentParties undly_instrument_parties = 59 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UndlyInstrumentParties getUndlyInstrumentParties(int index);
  /**
   * <code>repeated .Common.UndlyInstrumentParties undly_instrument_parties = 59 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  int getUndlyInstrumentPartiesCount();
  /**
   * <code>repeated .Common.UndlyInstrumentParties undly_instrument_parties = 59 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  java.util.List<? extends org.fixprotocol.components.UndlyInstrumentPartiesOrBuilder> 
      getUndlyInstrumentPartiesOrBuilderList();
  /**
   * <code>repeated .Common.UndlyInstrumentParties undly_instrument_parties = 59 [(.fix.field_added) = VERSION_FIX_4_4];</code>
   */
  org.fixprotocol.components.UndlyInstrumentPartiesOrBuilder getUndlyInstrumentPartiesOrBuilder(
      int index);

  /**
   * <code>.Common.UnderlyingExerciseStyleEnum underlying_exercise_style = 60 [(.fix.tag) = 1419, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  int getUnderlyingExerciseStyleValue();
  /**
   * <code>.Common.UnderlyingExerciseStyleEnum underlying_exercise_style = 60 [(.fix.tag) = 1419, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.UnderlyingExerciseStyleEnum getUnderlyingExerciseStyle();

  /**
   * <code>.fix.LocalTimeOnly underlying_maturity_time = 61 [(.fix.tag) = 1213, (.fix.type) = DATATYPE_TZ_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  boolean hasUnderlyingMaturityTime();
  /**
   * <code>.fix.LocalTimeOnly underlying_maturity_time = 61 [(.fix.tag) = 1213, (.fix.type) = DATATYPE_TZ_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.Fix.LocalTimeOnly getUnderlyingMaturityTime();
  /**
   * <code>.fix.LocalTimeOnly underlying_maturity_time = 61 [(.fix.tag) = 1213, (.fix.type) = DATATYPE_TZ_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.Fix.LocalTimeOnlyOrBuilder getUnderlyingMaturityTimeOrBuilder();

  /**
   * <code>.Common.UnderlyingPriceUnitOfMeasureEnum underlying_price_unit_of_measure = 62 [(.fix.tag) = 1424, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  int getUnderlyingPriceUnitOfMeasureValue();
  /**
   * <code>.Common.UnderlyingPriceUnitOfMeasureEnum underlying_price_unit_of_measure = 62 [(.fix.tag) = 1424, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.UnderlyingPriceUnitOfMeasureEnum getUnderlyingPriceUnitOfMeasure();

  /**
   * <code>.fix.Decimal64 underlying_price_unit_of_measure_qty = 63 [(.fix.tag) = 1425, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  boolean hasUnderlyingPriceUnitOfMeasureQty();
  /**
   * <code>.fix.Decimal64 underlying_price_unit_of_measure_qty = 63 [(.fix.tag) = 1425, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingPriceUnitOfMeasureQty();
  /**
   * <code>.fix.Decimal64 underlying_price_unit_of_measure_qty = 63 [(.fix.tag) = 1425, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingPriceUnitOfMeasureQtyOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_unit_of_measure_qty = 64 [(.fix.tag) = 1423, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  boolean hasUnderlyingUnitOfMeasureQty();
  /**
   * <code>.fix.Decimal64 underlying_unit_of_measure_qty = 64 [(.fix.tag) = 1423, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingUnitOfMeasureQty();
  /**
   * <code>.fix.Decimal64 underlying_unit_of_measure_qty = 64 [(.fix.tag) = 1423, (.fix.type) = DATATYPE_QTY, (.fix.field_added) = VERSION_FIX_5_0];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingUnitOfMeasureQtyOrBuilder();

  /**
   * <code>.Common.UnderlyingContractMultiplierUnitEnum underlying_contract_multiplier_unit = 65 [(.fix.tag) = 1437, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 80];</code>
   */
  int getUnderlyingContractMultiplierUnitValue();
  /**
   * <code>.Common.UnderlyingContractMultiplierUnitEnum underlying_contract_multiplier_unit = 65 [(.fix.tag) = 1437, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 80];</code>
   */
  org.fixprotocol.components.UnderlyingContractMultiplierUnitEnum getUnderlyingContractMultiplierUnit();

  /**
   * <code>.Common.UnderlyingFlowScheduleTypeEnum underlying_flow_schedule_type = 66 [(.fix.tag) = 1441, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 80];</code>
   */
  int getUnderlyingFlowScheduleTypeValue();
  /**
   * <code>.Common.UnderlyingFlowScheduleTypeEnum underlying_flow_schedule_type = 66 [(.fix.tag) = 1441, (.fix.type) = DATATYPE_INT, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 80];</code>
   */
  org.fixprotocol.components.UnderlyingFlowScheduleTypeEnum getUnderlyingFlowScheduleType();

  /**
   * <code>fixed32 underlying_flow_schedule_type_reserved100plus = 67 [(.fix.tag) = 1441, (.fix.type) = DATATYPE_RESERVED100PLUS, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 80];</code>
   */
  int getUnderlyingFlowScheduleTypeReserved100Plus();

  /**
   * <code>.fix.Decimal64 underlying_attachment_point = 68 [(.fix.tag) = 1459, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  boolean hasUnderlyingAttachmentPoint();
  /**
   * <code>.fix.Decimal64 underlying_attachment_point = 68 [(.fix.tag) = 1459, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingAttachmentPoint();
  /**
   * <code>.fix.Decimal64 underlying_attachment_point = 68 [(.fix.tag) = 1459, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingAttachmentPointOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_detachment_point = 69 [(.fix.tag) = 1460, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  boolean hasUnderlyingDetachmentPoint();
  /**
   * <code>.fix.Decimal64 underlying_detachment_point = 69 [(.fix.tag) = 1460, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingDetachmentPoint();
  /**
   * <code>.fix.Decimal64 underlying_detachment_point = 69 [(.fix.tag) = 1460, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingDetachmentPointOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_notional_percentage_outstanding = 70 [(.fix.tag) = 1455, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  boolean hasUnderlyingNotionalPercentageOutstanding();
  /**
   * <code>.fix.Decimal64 underlying_notional_percentage_outstanding = 70 [(.fix.tag) = 1455, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingNotionalPercentageOutstanding();
  /**
   * <code>.fix.Decimal64 underlying_notional_percentage_outstanding = 70 [(.fix.tag) = 1455, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingNotionalPercentageOutstandingOrBuilder();

  /**
   * <code>.fix.Decimal64 underlying_original_notional_percentage_outstanding = 71 [(.fix.tag) = 1456, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  boolean hasUnderlyingOriginalNotionalPercentageOutstanding();
  /**
   * <code>.fix.Decimal64 underlying_original_notional_percentage_outstanding = 71 [(.fix.tag) = 1456, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64 getUnderlyingOriginalNotionalPercentageOutstanding();
  /**
   * <code>.fix.Decimal64 underlying_original_notional_percentage_outstanding = 71 [(.fix.tag) = 1456, (.fix.type) = DATATYPE_PERCENTAGE, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.Fix.Decimal64OrBuilder getUnderlyingOriginalNotionalPercentageOutstandingOrBuilder();

  /**
   * <code>.Common.UnderlyingRestructuringTypeEnum underlying_restructuring_type = 72 [(.fix.tag) = 1453, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  int getUnderlyingRestructuringTypeValue();
  /**
   * <code>.Common.UnderlyingRestructuringTypeEnum underlying_restructuring_type = 72 [(.fix.tag) = 1453, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.UnderlyingRestructuringTypeEnum getUnderlyingRestructuringType();

  /**
   * <code>.Common.UnderlyingSeniorityEnum underlying_seniority = 73 [(.fix.tag) = 1454, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  int getUnderlyingSeniorityValue();
  /**
   * <code>.Common.UnderlyingSeniorityEnum underlying_seniority = 73 [(.fix.tag) = 1454, (.fix.type) = DATATYPE_STRING, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 83];</code>
   */
  org.fixprotocol.components.UnderlyingSeniorityEnum getUnderlyingSeniority();

  public org.fixprotocol.components.UnderlyingInstrument.UnderlyingFlowScheduleTypeUnionCase getUnderlyingFlowScheduleTypeUnionCase();
}
