apiVersion: v1
kind: Service
metadata:
  labels:
    app: market-data-service
  name: market-data-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api 
    port: 50551
    protocol: TCP
    targetPort: 50551
  selector:
    app: market-data-service
  sessionAffinity: ClientIP
  type: NodePort

