apiVersion: v1
kind: Service
metadata:
  name: xosr-order-gateway
  labels:
    app: xosr-order-gateway
spec:
  ports:
  - port: 50551
    name: api
  clusterIP: None
  selector:
    app: xosr-order-gateway
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: xosr-order-gateway
  name: xosr-order-gateway
spec:
  serviceName: "xosr-order-gateway"
  replicas: 2
  selector:
    matchLabels:
      app: xosr-order-gateway
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: xosr-order-gateway
        servicetype: execution-venue 
        mic: XOSR
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: opentp
        env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.dockerRepo }}smart-router{{ .Values.dockerTag }}
        imagePullPolicy: Always
        name: xosr-order-gateway
        ports:
        - containerPort: 50551 
          name: api 
      serviceAccount: otpservice
      serviceAccountName: otpservice
