// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.fixprotocol.components;

/**
 * Protobuf type {@code Common.ComplexEventTimes}
 */
public  final class ComplexEventTimes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Common.ComplexEventTimes)
    ComplexEventTimesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ComplexEventTimes.newBuilder() to construct.
  private ComplexEventTimes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ComplexEventTimes() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ComplexEventTimes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ComplexEventTimes(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.fixprotocol.components.Fix.TimeOnly.Builder subBuilder = null;
            if (complexEventEndTime_ != null) {
              subBuilder = complexEventEndTime_.toBuilder();
            }
            complexEventEndTime_ = input.readMessage(org.fixprotocol.components.Fix.TimeOnly.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(complexEventEndTime_);
              complexEventEndTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.fixprotocol.components.Fix.TimeOnly.Builder subBuilder = null;
            if (complexEventStartTime_ != null) {
              subBuilder = complexEventStartTime_.toBuilder();
            }
            complexEventStartTime_ = input.readMessage(org.fixprotocol.components.Fix.TimeOnly.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(complexEventStartTime_);
              complexEventStartTime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.fixprotocol.components.Common.internal_static_Common_ComplexEventTimes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.fixprotocol.components.Common.internal_static_Common_ComplexEventTimes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.fixprotocol.components.ComplexEventTimes.class, org.fixprotocol.components.ComplexEventTimes.Builder.class);
  }

  public static final int COMPLEX_EVENT_END_TIME_FIELD_NUMBER = 1;
  private org.fixprotocol.components.Fix.TimeOnly complexEventEndTime_;
  /**
   * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return Whether the complexEventEndTime field is set.
   */
  public boolean hasComplexEventEndTime() {
    return complexEventEndTime_ != null;
  }
  /**
   * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return The complexEventEndTime.
   */
  public org.fixprotocol.components.Fix.TimeOnly getComplexEventEndTime() {
    return complexEventEndTime_ == null ? org.fixprotocol.components.Fix.TimeOnly.getDefaultInstance() : complexEventEndTime_;
  }
  /**
   * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   */
  public org.fixprotocol.components.Fix.TimeOnlyOrBuilder getComplexEventEndTimeOrBuilder() {
    return getComplexEventEndTime();
  }

  public static final int COMPLEX_EVENT_START_TIME_FIELD_NUMBER = 2;
  private org.fixprotocol.components.Fix.TimeOnly complexEventStartTime_;
  /**
   * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return Whether the complexEventStartTime field is set.
   */
  public boolean hasComplexEventStartTime() {
    return complexEventStartTime_ != null;
  }
  /**
   * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   * @return The complexEventStartTime.
   */
  public org.fixprotocol.components.Fix.TimeOnly getComplexEventStartTime() {
    return complexEventStartTime_ == null ? org.fixprotocol.components.Fix.TimeOnly.getDefaultInstance() : complexEventStartTime_;
  }
  /**
   * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
   */
  public org.fixprotocol.components.Fix.TimeOnlyOrBuilder getComplexEventStartTimeOrBuilder() {
    return getComplexEventStartTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (complexEventEndTime_ != null) {
      output.writeMessage(1, getComplexEventEndTime());
    }
    if (complexEventStartTime_ != null) {
      output.writeMessage(2, getComplexEventStartTime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (complexEventEndTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getComplexEventEndTime());
    }
    if (complexEventStartTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getComplexEventStartTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.fixprotocol.components.ComplexEventTimes)) {
      return super.equals(obj);
    }
    org.fixprotocol.components.ComplexEventTimes other = (org.fixprotocol.components.ComplexEventTimes) obj;

    if (hasComplexEventEndTime() != other.hasComplexEventEndTime()) return false;
    if (hasComplexEventEndTime()) {
      if (!getComplexEventEndTime()
          .equals(other.getComplexEventEndTime())) return false;
    }
    if (hasComplexEventStartTime() != other.hasComplexEventStartTime()) return false;
    if (hasComplexEventStartTime()) {
      if (!getComplexEventStartTime()
          .equals(other.getComplexEventStartTime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasComplexEventEndTime()) {
      hash = (37 * hash) + COMPLEX_EVENT_END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getComplexEventEndTime().hashCode();
    }
    if (hasComplexEventStartTime()) {
      hash = (37 * hash) + COMPLEX_EVENT_START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getComplexEventStartTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.fixprotocol.components.ComplexEventTimes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.fixprotocol.components.ComplexEventTimes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Common.ComplexEventTimes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Common.ComplexEventTimes)
      org.fixprotocol.components.ComplexEventTimesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.fixprotocol.components.Common.internal_static_Common_ComplexEventTimes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.fixprotocol.components.Common.internal_static_Common_ComplexEventTimes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.fixprotocol.components.ComplexEventTimes.class, org.fixprotocol.components.ComplexEventTimes.Builder.class);
    }

    // Construct using org.fixprotocol.components.ComplexEventTimes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (complexEventEndTimeBuilder_ == null) {
        complexEventEndTime_ = null;
      } else {
        complexEventEndTime_ = null;
        complexEventEndTimeBuilder_ = null;
      }
      if (complexEventStartTimeBuilder_ == null) {
        complexEventStartTime_ = null;
      } else {
        complexEventStartTime_ = null;
        complexEventStartTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.fixprotocol.components.Common.internal_static_Common_ComplexEventTimes_descriptor;
    }

    @java.lang.Override
    public org.fixprotocol.components.ComplexEventTimes getDefaultInstanceForType() {
      return org.fixprotocol.components.ComplexEventTimes.getDefaultInstance();
    }

    @java.lang.Override
    public org.fixprotocol.components.ComplexEventTimes build() {
      org.fixprotocol.components.ComplexEventTimes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.fixprotocol.components.ComplexEventTimes buildPartial() {
      org.fixprotocol.components.ComplexEventTimes result = new org.fixprotocol.components.ComplexEventTimes(this);
      if (complexEventEndTimeBuilder_ == null) {
        result.complexEventEndTime_ = complexEventEndTime_;
      } else {
        result.complexEventEndTime_ = complexEventEndTimeBuilder_.build();
      }
      if (complexEventStartTimeBuilder_ == null) {
        result.complexEventStartTime_ = complexEventStartTime_;
      } else {
        result.complexEventStartTime_ = complexEventStartTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.fixprotocol.components.ComplexEventTimes) {
        return mergeFrom((org.fixprotocol.components.ComplexEventTimes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.fixprotocol.components.ComplexEventTimes other) {
      if (other == org.fixprotocol.components.ComplexEventTimes.getDefaultInstance()) return this;
      if (other.hasComplexEventEndTime()) {
        mergeComplexEventEndTime(other.getComplexEventEndTime());
      }
      if (other.hasComplexEventStartTime()) {
        mergeComplexEventStartTime(other.getComplexEventStartTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.fixprotocol.components.ComplexEventTimes parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.fixprotocol.components.ComplexEventTimes) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.fixprotocol.components.Fix.TimeOnly complexEventEndTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fixprotocol.components.Fix.TimeOnly, org.fixprotocol.components.Fix.TimeOnly.Builder, org.fixprotocol.components.Fix.TimeOnlyOrBuilder> complexEventEndTimeBuilder_;
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     * @return Whether the complexEventEndTime field is set.
     */
    public boolean hasComplexEventEndTime() {
      return complexEventEndTimeBuilder_ != null || complexEventEndTime_ != null;
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     * @return The complexEventEndTime.
     */
    public org.fixprotocol.components.Fix.TimeOnly getComplexEventEndTime() {
      if (complexEventEndTimeBuilder_ == null) {
        return complexEventEndTime_ == null ? org.fixprotocol.components.Fix.TimeOnly.getDefaultInstance() : complexEventEndTime_;
      } else {
        return complexEventEndTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder setComplexEventEndTime(org.fixprotocol.components.Fix.TimeOnly value) {
      if (complexEventEndTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        complexEventEndTime_ = value;
        onChanged();
      } else {
        complexEventEndTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder setComplexEventEndTime(
        org.fixprotocol.components.Fix.TimeOnly.Builder builderForValue) {
      if (complexEventEndTimeBuilder_ == null) {
        complexEventEndTime_ = builderForValue.build();
        onChanged();
      } else {
        complexEventEndTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder mergeComplexEventEndTime(org.fixprotocol.components.Fix.TimeOnly value) {
      if (complexEventEndTimeBuilder_ == null) {
        if (complexEventEndTime_ != null) {
          complexEventEndTime_ =
            org.fixprotocol.components.Fix.TimeOnly.newBuilder(complexEventEndTime_).mergeFrom(value).buildPartial();
        } else {
          complexEventEndTime_ = value;
        }
        onChanged();
      } else {
        complexEventEndTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder clearComplexEventEndTime() {
      if (complexEventEndTimeBuilder_ == null) {
        complexEventEndTime_ = null;
        onChanged();
      } else {
        complexEventEndTime_ = null;
        complexEventEndTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public org.fixprotocol.components.Fix.TimeOnly.Builder getComplexEventEndTimeBuilder() {
      
      onChanged();
      return getComplexEventEndTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public org.fixprotocol.components.Fix.TimeOnlyOrBuilder getComplexEventEndTimeOrBuilder() {
      if (complexEventEndTimeBuilder_ != null) {
        return complexEventEndTimeBuilder_.getMessageOrBuilder();
      } else {
        return complexEventEndTime_ == null ?
            org.fixprotocol.components.Fix.TimeOnly.getDefaultInstance() : complexEventEndTime_;
      }
    }
    /**
     * <code>.fix.TimeOnly complex_event_end_time = 1 [(.fix.tag) = 1496, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fixprotocol.components.Fix.TimeOnly, org.fixprotocol.components.Fix.TimeOnly.Builder, org.fixprotocol.components.Fix.TimeOnlyOrBuilder> 
        getComplexEventEndTimeFieldBuilder() {
      if (complexEventEndTimeBuilder_ == null) {
        complexEventEndTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.fixprotocol.components.Fix.TimeOnly, org.fixprotocol.components.Fix.TimeOnly.Builder, org.fixprotocol.components.Fix.TimeOnlyOrBuilder>(
                getComplexEventEndTime(),
                getParentForChildren(),
                isClean());
        complexEventEndTime_ = null;
      }
      return complexEventEndTimeBuilder_;
    }

    private org.fixprotocol.components.Fix.TimeOnly complexEventStartTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fixprotocol.components.Fix.TimeOnly, org.fixprotocol.components.Fix.TimeOnly.Builder, org.fixprotocol.components.Fix.TimeOnlyOrBuilder> complexEventStartTimeBuilder_;
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     * @return Whether the complexEventStartTime field is set.
     */
    public boolean hasComplexEventStartTime() {
      return complexEventStartTimeBuilder_ != null || complexEventStartTime_ != null;
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     * @return The complexEventStartTime.
     */
    public org.fixprotocol.components.Fix.TimeOnly getComplexEventStartTime() {
      if (complexEventStartTimeBuilder_ == null) {
        return complexEventStartTime_ == null ? org.fixprotocol.components.Fix.TimeOnly.getDefaultInstance() : complexEventStartTime_;
      } else {
        return complexEventStartTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder setComplexEventStartTime(org.fixprotocol.components.Fix.TimeOnly value) {
      if (complexEventStartTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        complexEventStartTime_ = value;
        onChanged();
      } else {
        complexEventStartTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder setComplexEventStartTime(
        org.fixprotocol.components.Fix.TimeOnly.Builder builderForValue) {
      if (complexEventStartTimeBuilder_ == null) {
        complexEventStartTime_ = builderForValue.build();
        onChanged();
      } else {
        complexEventStartTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder mergeComplexEventStartTime(org.fixprotocol.components.Fix.TimeOnly value) {
      if (complexEventStartTimeBuilder_ == null) {
        if (complexEventStartTime_ != null) {
          complexEventStartTime_ =
            org.fixprotocol.components.Fix.TimeOnly.newBuilder(complexEventStartTime_).mergeFrom(value).buildPartial();
        } else {
          complexEventStartTime_ = value;
        }
        onChanged();
      } else {
        complexEventStartTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public Builder clearComplexEventStartTime() {
      if (complexEventStartTimeBuilder_ == null) {
        complexEventStartTime_ = null;
        onChanged();
      } else {
        complexEventStartTime_ = null;
        complexEventStartTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public org.fixprotocol.components.Fix.TimeOnly.Builder getComplexEventStartTimeBuilder() {
      
      onChanged();
      return getComplexEventStartTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    public org.fixprotocol.components.Fix.TimeOnlyOrBuilder getComplexEventStartTimeOrBuilder() {
      if (complexEventStartTimeBuilder_ != null) {
        return complexEventStartTimeBuilder_.getMessageOrBuilder();
      } else {
        return complexEventStartTime_ == null ?
            org.fixprotocol.components.Fix.TimeOnly.getDefaultInstance() : complexEventStartTime_;
      }
    }
    /**
     * <code>.fix.TimeOnly complex_event_start_time = 2 [(.fix.tag) = 1495, (.fix.type) = DATATYPE_UTC_TIME_ONLY, (.fix.field_added) = VERSION_FIX_5_0SP1, (.fix.field_added_ep) = 92];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.fixprotocol.components.Fix.TimeOnly, org.fixprotocol.components.Fix.TimeOnly.Builder, org.fixprotocol.components.Fix.TimeOnlyOrBuilder> 
        getComplexEventStartTimeFieldBuilder() {
      if (complexEventStartTimeBuilder_ == null) {
        complexEventStartTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.fixprotocol.components.Fix.TimeOnly, org.fixprotocol.components.Fix.TimeOnly.Builder, org.fixprotocol.components.Fix.TimeOnlyOrBuilder>(
                getComplexEventStartTime(),
                getParentForChildren(),
                isClean());
        complexEventStartTime_ = null;
      }
      return complexEventStartTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Common.ComplexEventTimes)
  }

  // @@protoc_insertion_point(class_scope:Common.ComplexEventTimes)
  private static final org.fixprotocol.components.ComplexEventTimes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.fixprotocol.components.ComplexEventTimes();
  }

  public static org.fixprotocol.components.ComplexEventTimes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ComplexEventTimes>
      PARSER = new com.google.protobuf.AbstractParser<ComplexEventTimes>() {
    @java.lang.Override
    public ComplexEventTimes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ComplexEventTimes(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ComplexEventTimes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ComplexEventTimes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.fixprotocol.components.ComplexEventTimes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

